---
title: Cluster Using Same Genes Across Replicates
author: Justin M. Fear
email: justin.m.fear@gmail.com
---

```{r, include=FALSE}
knitr::opts_chunk$set(collapse=TRUE, warning=FALSE, message=FALSE,
                      bootstrap.show.code=FALSE, bootstrap.show.output=FALSE,
                      fig.ext='png')
```

```{r library}
# Import R libraries
library(Seurat)
library(dplyr)
library(Matrix)
```

```{r r1, cache=TRUE}
# Load the 10x dataset Rep 1
tenX.data <- Read10X(data.dir='../output/testis1_force/outs/filtered_gene_bc_matrices/dm6.16')
colnames(tenX.data) <- paste(colnames(tenX.data), 'rep1', sep='_')
r1 <- CreateSeuratObject(raw.data=tenX.data, min.cells=3, min.genes=200, project='GroupCluster')
r1@meta.data$rep <- 'rep1'
r1 <- FilterCells(object=r1, subset.names=c("nGene"), low.thresholds=c(200), high.thresholds=c(6000))
r1 <- NormalizeData(object=r1, normalization.method="LogNormalize", scale.factor=1e4)
r1 <- ScaleData(object=r1, vars.to.regress=c("nUMI"), display.progress=FALSE)
```

```{r r2, cache=TRUE}
# Load the 10x dataset Rep 2
tenX.data <- Read10X(data.dir='../output/testis2_force/outs/filtered_gene_bc_matrices/dm6.16')
colnames(tenX.data) <- paste(colnames(tenX.data), 'rep2', sep='_')
r2 <- CreateSeuratObject(raw.data=tenX.data, min.cells=3, min.genes=200, project='GroupCluster')
r2@meta.data$rep <- 'rep2'
r2 <- FilterCells(object=r2, subset.names=c("nGene"), low.thresholds=c(200), high.thresholds=c(6000))
r2 <- NormalizeData(object=r2, normalization.method="LogNormalize", scale.factor=1e4)
r2 <- ScaleData(object=r2, vars.to.regress=c("nUMI"), display.progress=FALSE)
```

```{r r3, cache=TRUE}
# Load the 10x dataset Rep 3
tenX.data <- Read10X(data.dir='../output/testis3_force/outs/filtered_gene_bc_matrices/dm6.16')
colnames(tenX.data) <- paste(colnames(tenX.data), 'rep3', sep='_')
r3 <- CreateSeuratObject(raw.data=tenX.data, min.cells=3, min.genes=200, project='GroupCluster')
r3@meta.data$rep <- 'rep3'
r3 <- FilterCells(object=r3, subset.names=c("nGene"), low.thresholds=c(200), high.thresholds=c(6000))
r3 <- NormalizeData(object=r3, normalization.method="LogNormalize", scale.factor=1e4)
r3 <- ScaleData(object=r3, vars.to.regress=c("nUMI"), display.progress=FALSE)
```

```{r variable, cache=TRUE}
# Find the highly variable genes
r1 <- FindVariableGenes(object=r1, mean.function=ExpMean, dispersion.function=LogVMR, do.plot=FALSE, x.low.cutoff=0.01, x.high.cutoff=3, y.cutoff=0.5, y.high.cutoff=Inf)
r2 <- FindVariableGenes(object=r2, mean.function=ExpMean, dispersion.function=LogVMR, do.plot=FALSE, x.low.cutoff=0.01, x.high.cutoff=3, y.cutoff=0.5, y.high.cutoff=Inf)
r3 <- FindVariableGenes(object=r3, mean.function=ExpMean, dispersion.function=LogVMR, do.plot=FALSE, x.low.cutoff=0.01, x.high.cutoff=3, y.cutoff=0.5, y.high.cutoff=Inf)
g.1 <- head(rownames(r1@hvg.info), 1000)
g.2 <- head(rownames(r2@hvg.info), 1000)
g.3 <- head(rownames(r3@hvg.info), 1000)

genes.use <- unique(c(g.1, g.2, g.3))
genes.use <- intersect(genes.use, rownames(r1@scale.data))
genes.use <- intersect(genes.use, rownames(r2@scale.data))
genes.use <- intersect(genes.use, rownames(r3@scale.data))
```

```{r ccaMulti, cache=TRUE}
combined = RunMultiCCA(list(r1, r2, r3), genes.use=genes.use, num.cc=3)
```

```{r plotMulti}
p1 <- DimPlot(object=combined, reduction.use='cca', group.by='rep', pt.size=0.5, do.return=TRUE)
p2 <- VlnPlot(object=combined, features.plot='CC1', group.by='rep', do.return=TRUE)
plot_grid(p1, p2)
```


```{r align, cache=TRUE}
combined <- AlignSubspace(combined, reduction.type = "cca", grouping.var = "rep", dims.align = 1:3)
```

```{r plotAlign}
p1 <- VlnPlot(object=combined, features.plot='ACC1', group.by='rep', do.return=TRUE)
p2 <- VlnPlot(object=combined, features.plot='ACC2', group.by='rep', do.return=TRUE)
plot_grid(p1, p2)
```


```{r tsne}
combined <- RunTSNE(combined, reduction.use = "cca.aligned", dims.use = 1:3, do.fast = T)
combined <- FindClusters(combined, reduction.type = "cca.aligned", resolution = 0.6, dims.use = 1:3)
```

```{r plotTsne}
p1 <- TSNEPlot(combined, do.return = T, pt.size = 0.5, group.by = "rep")
p2 <- TSNEPlot(combined, do.label = T, do.return = T, pt.size = 0.5)
plot_grid(p1, p2)
p1
p2
```
