---
title: DropletUtils
author: Justin Fear
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse=TRUE, warning=FALSE, message=FALSE, cache.lazy=FALSE,
                      bootstrap.show.code=FALSE, bootstrap.show.output=FALSE)
```

```{r load_library}
library(DropletUtils)
library(dplyr)
library(feather)
library(ggplot2)
theme_set(theme_bw())
```

```{r snakemake, include=FALSE, eval=TRUE}
DATA_DIR <- dirname(snakemake@input[[1]])
OUTDIR <- dirname(snakemake@output[[1]])
SAMPLE <- snakemake@wildcards[['sample']]
REP <- paste0('rep', gsub('.*(\\d)', '\\1', SAMPLE), '_')
```

```{r debug, include=FALSE, eval=FALSE}
DATA_DIR <- '../../output/cellranger-wf/testis1/outs/raw_gene_bc_matrices/dmelr6-24'
OUTDIR <- '../../output/cellranger-wf/dropletutils'
SAMPLE <- 'testis1'
REP <- paste0('rep', gsub('.*(\\d)', '\\1', SAMPLE), '_')
```

# `r SAMPLE`

**Data Used:** `r DATA_DIR`

## Load 10x data
```{r load_data}
tenX <- read10xCounts(DATA_DIR)
```

## Determine Barcode Ranks
```{r barcode_ranks}
barcode_rank <- barcodeRanks(counts(tenX))
```

## Estimate Empty Droplets

If there is a large number of `Limited = TRUE` and `SIGNIFICANT = FALSE` then repeat with more permutations.

```{r empty_droplets}
set.seed(42)
empty_drops <- emptyDrops(counts(tenX))
is_cell <- empty_drops$FDR <= 0.01
is_cell[is.na(is_cell)] <- FALSE
table(Limited = empty_drops$Limited, Signifcant = is_cell)
```

```{r fig.width=12}
ggplot(as.data.frame(empty_drops), aes(x = Total, y = -LogProb, color=is_cell)) + 
    geom_point() +
    scale_color_manual(values = c('lightgray', 'black')) + 
    labs(x = 'Total UMI', y = '-Log P-Value', title = SAMPLE) +
    scale_x_log10() + 
    scale_y_log10()

ggsave(file.path(OUTDIR, paste0(SAMPLE, '_pval.png')))
```


```{r}
df <- as.data.frame(barcode_rank)
df$is_cell <- is_cell
df$barcode <- tenX@colData$Barcode
df$cell_id <- gsub('(.*?)-1', paste0(REP, '\\1'), df$barcode)
df <- df %>% select(cell_id, barcode, everything())
write_feather(df, file.path(OUTDIR, paste0(SAMPLE, '_cell_metadta.feather')))
write.table(df, file = file.path(OUTDIR, paste0(SAMPLE, '_cell_metadta.tsv')), sep = '\t', quote = FALSE, row.names = FALSE)
```


```{r fig.width=12}
ggplot(df, aes(x=rank, y=total, color=is_cell)) + 
    geom_point() + 
    scale_x_log10() + 
    scale_y_log10() +
    theme_bw() +
    geom_hline(yintercept = barcode_rank$knee, linetype = 2, color = "dodgerBlue") +
    geom_hline(yintercept = barcode_rank$inflection, linetype = 2, color = "forestgreen") + 
    scale_color_manual(values = c('lightgray', 'black')) +
    labs(x = "Ranks", y = "Total UMI", title = paste0(SAMPLE, ' (DropletUtils)'))
ggsave(file.path(OUTDIR, paste0(SAMPLE, '_bc_rank.png')))
```
