data_pattern:
  cellranger3-wf: '../output/cellranger3-wf/{sample}/outs/filtered_feature_bc_matrix/matrix.mtx'
  cellselection-wf: '../output/cellselection-wf/{sample}/matrix.mtx'

cellranger:
  - 'cellranger3-wf'
  - 'cellselection-wf'

cutoffs:
  - 'gl-200_gh-None_ul-None_uh-None'
  - 'gl-200_gh-None_ul-None_uh-1e5'

resolutions:
  - 0.4
  - 0.6
  - 1

seurat_file_types:
  metadata: cell_id
  raw: FBgn
  normalized_read_counts: FBgn
  scaled: FBgn
  clusters: cell_id
  tsne: cell_id
  biomarkers_res.0.4: FBgn
  biomarkers_res.0.6: FBgn
  biomarkers_res.1: FBgn
  zscore: FBgn
