fn_clean_exts:
  #- '.cutadapt'
  - ']'
  - '.log'
  - '.bam.bowtie2'
  - '.gz'
  - '.fastq'
  - '.salmon'
  - '_R1'

sp:
  fastq_screen:
    fn: '*.screen.txt'
  picard/rnaseqmetrics:
    contents_re: '.*picard\.analysis\.[Rr]na[Ss]eq[Mm]etrics.*'
    shared: true
  picard/markdups:
    contents_re: '.*picard\.sam\.[Dd]uplication[Mm]etrics.*'
    contents: ''
    shared: true
