cellranger:
  raw: '{sample_dir}/{sample}/outs/raw_gene_bc_matrices'
  raw_h5: '{sample_dir}/{sample}/outs/raw_gene_bc_matrices_h5.h5'
  filtered: '{sample_dir}/{sample}/outs/filtered_gene_bc_matrices'
  filtered_h5: '{sample_dir}/{sample}/outs/filtered_gene_bc_matrices_h5.h5'
  bam: '{sample_dir}/{sample}/outs/possorted_genome_bam.bam'
  bai: '{sample_dir}/{sample}/outs/possorted_genome_bam.bam.bai'

cellranger_force:
  raw: '{sample_dir}/{sample}_force/outs/raw_gene_bc_matrices'
  raw_h5: '{sample_dir}/{sample}_force/outs/raw_gene_bc_matrices_h5.h5'
  filtered: '{sample_dir}/{sample}_force/outs/filtered_gene_bc_matrices'
  filtered_h5: '{sample_dir}/{sample}_force/outs/filtered_gene_bc_matrices_h5.h5'
  bam: '{sample_dir}/{sample}_force/outs/possorted_genome_bam.bam'
  bai: '{sample_dir}/{sample}_force/outs/possorted_genome_bam.bam.bai'
