seurat_dir: '../output/scrnaseq-wf/scrnaseq_combine_force'
styles:
 - paper
resolution: 'res.0.6'
alpha: 0.001
lit_genes_long:
#GSC, spermatogonia, early spermatocytes (12)
  - 'vas'
  - 'bam'
  - 'Phf7'
  - 'CG11697'
  - 'p53'
  - 'nos'
  - 'bgcn'
  - 'tut'
  - 'Rbp9'
  - 'peb'
  - 'tej'
  - 'Marf'
# Later spermatocytes and spermatids (22)
  - 'aly'
  - 'nht'
  - 'soti'
  - 'dj'
  - 'ocn'
  - 'can'
  - 'fzo'
  - 'bol'
  - 'mle'
  - 'mia'
  - 'CG3927'
  - 'sunz'
  - 'sowi'
  - 'd-cup'
  - 'c-cup'
  - 'wa-cup'
  - 'p-cup'
  - 'r-cup'
  - 'oys'
  - 'topi'
  - 'sa'
  - 'CG8368'
# Enriched in CySC lineage (24)
  - 'tj'
  - 'eya'
  - 'zfh1'
  - 'vn'
  - 'foxo'
  - 'apt'
  - 'ImpL2'
  - 'Wnt4'
  - 'Nrt'
  - 'bnb'
  - 'neur'
  - 'robo2'
  - 'EcR'
  - 'gbb'
  - 'spict'
  - 'puc'
  - 'sev'
  - 'hui'
  - 'sano'
  - 'glob1'
  - 'Eip93F'
  - 'fax'
  - 'kek1'
  - 'so'
# Terminal epithelia (9)
  - 'nord'
  - 'retn'
  - 'abd-A'
  - 'Abd-B'
  - 'Wnt2'
  - 'Six4'
  - 'CG18628'
  - 'MtnA'
  - 'N'
# Pigment cells (4)
  - 'bw'
  - 'vkg'
  - 'Sox100B'
  - 'ems'
# Genes in multiple cell types (14)
  #  - 'chinmo'
  #  - 'His2Av'
  #  - 'Diap1'
  #  - 'Diap2'
  #  - 'Socs36E'
  #  - 'hdc'
  #  - 'how'
  #  - 'msi'
  #  - 'ken'
  #  - 'piwi'
# Other important markers (3)
  #  - 'stg'
  #  - 'twe'
  #  - 'esg'

lit_genes_short:
 #GSC, spermatogonia, early spermatocytes
 - 'vas'
 - 'bam'
 # Early spermatocytes
 - 'aly'
 - 'nht'
 # Later spermatocytes and spermatids
 - 'dj'
 - 'ocn'
 # Enriched in CySC lineage
 - 'tj'
 - 'eya'
 # Terminal epithelia
 - 'nord'
 # Pigment cells
 - 'bw'

protein_trap_genes:
  - 'ADD1'
  - 'Ance'
  - 'CG11044'
  - 'CG17349'
  - 'CG17646'
  - 'CG3277'
  - 'CG42321'
  - 'CG43088'
  - 'CG43373'
  - 'CG6356'
  - 'CG8036'
  - 'CG8851'
  - 'CG9747'
  - 'CadN'
  - 'DIP-delta'
  - 'Dek'
  - 'Efa6'
  - 'Fas3'
  - 'Fs(2)Ket'
  - 'ImpL2'
  - 'LRP1'
  - 'Mapmodulin'
  - 'Mi-2'
  - 'NFAT'
  - 'NetA'
  - 'Nrg'
  - 'Pdcd4'
  - 'Pde11'
  - 'Piezo'
  - 'Ptp4E'
  - 'Pvr'
  - 'Rab3'
  - 'Reck'
  - 'SRPK'
  - 'Sap-r'
  - 'Sox102F'
  - 'Ten-a'
  - 'Ten-m'
  - 'Tep2'
  - 'Vha68-3'
  - 'Wdr62'
  - 'bbg'
  - 'bol'
  - 'cindr'
  - 'dlp'
  - 'dpr17'
  - 'dpr3'
  - 'dsx'
  - 'e(y)3'
  - 'eIF5B'
  - 'egr'
  - 'foxo'
  - 'fru'
  - 'hid'
  - 'klu'
  - 'mbl'
  - 'nkd'
  - 'nord'
  - 'osa'
  - 'p130CAS'
  - 'p53'
  - 'ppan'
  - 'sdk'
  - 'spir'
  - 'stai'
  - 'stg'
  - 'svp'
  - 'tok'
  - 'tutl'
  - 'twin'
  - 'wnd'

msl_genes:
 # Dosage compensation genes from FlyBase MSL complex
  - FBgn0002774 # mle
  - FBgn0002775 # msl-3
  - FBgn0005616 # msl-2
  - FBgn0005617 # msl-1
  - FBgn0014340 # mof
  - FBgn0019660 # rox2
  - FBgn0019661 # rox1

