# Expression Counts tables
Raw Counts:
  description: 'Raw counts summed to the cell type by replicate level.'
  fname: '../output/scrnaseq-wf/raw_by_cluster_w_rep.parquet'
  index:
    FBgn: 'FlyBase gene ID'
    gene_symbol: 'FlyBase Gene Symbol'
    chrom: 'Chromosome Arm'
  columns:
    Cluster ID: 'See above for description of cell type names.'
    Replicate ID: 'Which biological replicate the cells came from.'
  rows: 'genes'

Seurat Normalized Counts:
  description: 'Seurat normalized counts summed to the cell type by replicate level.'
  fname: '../output/scrnaseq-wf/seurat_norm_by_cluster_w_rep.parquet'
  index:
    FBgn: 'FlyBase gene ID'
    gene_symbol: 'FlyBase Gene Symbol'
    chrom: 'Chromosome Arm'
  columns:
    Cluster ID: 'See above for description of cell type names.'
    Replicate ID: 'Which biological replicate the cells came from.'
  rows: 'genes'

RPKM Normalized Counts:
  description: 'RPKM normalized counts summed to the cell type by replicate level.'
  fname: '../output/scrnaseq-wf/rpkm_by_rep.parquet'
  index:
    FBgn: 'FlyBase gene ID'
    gene_symbol: 'FlyBase Gene Symbol'
    chrom: 'Chromosome Arm'
  columns:
    Cluster ID: 'See above for description of cell type names.'
    Replicate ID: 'Which biological replicate the cells came from.'
  rows: 'genes'

TPM Normalized Counts:
  description: 'TPM normalized counts summed to the cell type by replicate level.'
  fname: '../output/scrnaseq-wf/tpm_by_rep.parquet'
  index:
    FBgn: 'FlyBase gene ID'
    gene_symbol: 'FlyBase Gene Symbol'
    chrom: 'Chromosome Arm'
  columns:
    Cluster ID: 'See above for description of cell type names.'
    Replicate ID: 'Which biological replicate the cells came from.'
  rows: 'genes'

TPM Zscores:
  description: 'Z-scores calculated using TPM normalized counts summed to the cell type by replicate level.'
  fname: '../output/scrnaseq-wf/tpm_zscore_by_rep.parquet'
  index:
    FBgn: 'FlyBase gene ID'
    gene_symbol: 'FlyBase Gene Symbol'
    chrom: 'Chromosome Arm'
  columns:
    Cluster ID: 'See above for description of cell type names.'
    Replicate ID: 'Which biological replicate the cells came from.'
  rows: 'genes'

# Seurat output
Biomarker List:
  description: 'The cell type biomarker list generated by Seurat. This list is based on differential up regulation when comparing each cluster to all other cells.'
  index:
    FBgn: 'FlyBase gene ID'
    gene_symbol: 'FlyBase Gene Symbol'
    chrom: 'Chromosome Arm'
  columns:
    Cluster ID: 'See above for description of cell type names.'
    avg_logFC: 'The average log fold change'
    p_val: 'P-value for the comparison.'
    p_val_adj: 'FDR adjusted p-value'
    pct.1: 'The percent of cells with this gene in this cell type.'
    pct.2: 'The percent of cells with this gene in all other cells not in this cell type.'
  rows: 'genes'

tSNE:
  description: 'Coordinates for plotting the tSNE. This is output by Seurat.'
  index:
    cell_id: 'The individual cell id, prefixed with the replicate id.'
  columns:
    tSNE_1: 'The tSNE coordinate on the first axis.'
    tSNE_2: 'The tSNE coordinate on the second axis.'
  rows: 'individual cells'

# More Differential Expression
SP vs Spermatocytes:
  description: 'Seurat output for comparing SP vs all spermatocyte clusters.'
  index:
    FBgn: 'FlyBase gene ID'
    gene_symbol: 'FlyBase Gene Symbol'
    chrom: 'Chromosome Arm'
  columns:
    avg_logFC: 'The average log fold change'
    p_val: 'P-value for the comparison.'
    p_val_adj: 'FDR adjusted p-value'
    pct.1: 'The percent of cells with this gene in this cell type.'
    pct.2: 'The percent of cells with this gene in all other cells not in this cell type.'
  rows: 'genes'

SP vs E1°:
  description: 'Seurat output for comparing SP vs E1°.'
  index:
    FBgn: 'FlyBase gene ID'
    gene_symbol: 'FlyBase Gene Symbol'
    chrom: 'Chromosome Arm'
  columns:
    avg_logFC: 'The average log fold change'
    p_val: 'P-value for the comparison.'
    p_val_adj: 'FDR adjusted p-value'
    pct.1: 'The percent of cells with this gene in this cell type.'
    pct.2: 'The percent of cells with this gene in all other cells not in this cell type.'
  rows: 'genes'

E1° vs M1°:
  description: 'Seurat output for comparing E1° vs M1°.'
  index:
    FBgn: 'FlyBase gene ID'
    gene_symbol: 'FlyBase Gene Symbol'
    chrom: 'Chromosome Arm'
  columns:
    avg_logFC: 'The average log fold change'
    p_val: 'P-value for the comparison.'
    p_val_adj: 'FDR adjusted p-value'
    pct.1: 'The percent of cells with this gene in this cell type.'
    pct.2: 'The percent of cells with this gene in all other cells not in this cell type.'
  rows: 'genes'

M1° vs L1°:
  description: 'Seurat output for comparing M1° vs L1°.'
  index:
    FBgn: 'FlyBase gene ID'
    gene_symbol: 'FlyBase Gene Symbol'
    chrom: 'Chromosome Arm'
  columns:
    avg_logFC: 'The average log fold change'
    p_val: 'P-value for the comparison.'
    p_val_adj: 'FDR adjusted p-value'
    pct.1: 'The percent of cells with this gene in this cell type.'
    pct.2: 'The percent of cells with this gene in all other cells not in this cell type.'
  rows: 'genes'

# Autosome Result
Autosome Ratio Data:
  description: 'Data for looking at X and 4th to autosome ratios.'
  index:
    cell_id: 'The individual cell id, prefixed with the replicate id.'
    Cluster ID: 'See above for description of cell type names.'
    Replicate ID: 'Which biological replicate the cells came from.'
  columns:
    chrX: 'Total expression on X.'
    chr2L: 'Total expression on 2L.'
    chr2R: 'Total expression on 2R.'
    chr3L: 'Total expression on 3L.'
    chr3R: 'Total expression on 3R.'
    chr4: 'Total expression on 4.'
    chrY: 'Total expression on Y.'
    x_to_a_ratio: 'The ratio of X / (2L + 2R + 3L + 3R)'
    fourth_to_a_ratio: 'The ratio of 4 / (2L + 2R + 3L + 3R)'
    y_to_a_ratio: 'The ratio of Y / (2L + 2R + 3L + 3R)'
  rows: 'individual cells'

Autosome Ratio Results:
  description: 'Results from running a permutation test looking at X and 4th to autosome ratios.'
  index:
    Cluster ID: 'See above for description of cell type names.'
  columns:
    pval_x: 'P-value for X / (2L + 2R + 3L + 3R) permutation test.'
    pval_4: 'P-value for 4 / (2L + 2R + 3L + 3R) permutation test.'
    pval_y: 'P-value for Y / (2L + 2R + 3L + 3R) permutation test.'
  rows: 'Germline Clusters'


