
rule all:
    input: 
        "../output/response-to-review-wf/prop_cells_on_commonly_expressed.tsv",


rule prop_cells_on_commonly_expressed:
    """Proportion of cells expressing commonly expressed genes

    Table: commonly expressed genes x cluster
    """
    input: 
        commonly_expressed="../output/cellselection-wf/commonly_expressed_genes.pkl",
        clusters="../output//seurat3-cluster-wf/combined_n3_clusters.feather",
        raw="../output/cellselection-wf/raw.feather",
        tau="../output/expression-atlas-wf/dmel_tau.feather",
        tsps="../output/expression-atlas-wf/dmel_tsps.feather",
    output: "../output/response-to-review-wf/prop_cells_on_commonly_expressed.tsv"
    script: "scripts/prop_cells_on-commonly_expressed.py"


rule dump_pickle_for_R:
    """Dump out pickle for easy import into R."""
    input: 
        expressed="../output/cellselection-wf/expressed_genes.pkl",
        commonly_expressed="../output/cellselection-wf/commonly_expressed_genes.pkl",
    output: 
        expressed=temp("../output/response-to-review-wf/expressed_genes.txt"),
        commonly_expressed=temp("../output/response-to-review-wf/commonly_expressed_genes.txt"),
    run:
        import joblib

        with open(output.expressed, "w") as fh:
            fh.write("\n".join(joblib.load(input.expressed)))

        with open(output.commonly_expressed, "w") as fh:
            fh.write("\n".join(joblib.load(input.commonly_expressed)))

rule commonly_expressed_GO:
    """Gene Ontology Analysis for commonly expressed genes."""
    input: 
        rmd="scripts/commonly_expressed_GO_analysis.Rmd",
        expressed=rules.dump_pickle_for_R.output.expressed,
        commonly_expressed=rules.dump_pickle_for_R.output.commonly_expressed,
    output:
        html = "../output/response-to-review-wf/commonly_expressed_GO_analysis.html",
    conda: "../envs/go_analysis.yaml"
    resources:
        mem_gb=lambda wildcards, attempt: attempt * 16,
        time_hr=lambda wildcards, attempt: attempt * 6
    script: "../scripts/rscript.py"
