---
title: Seurat2 Testis 4 Clustering
author: Justin Fear
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
output:
    html_document:
        self_contained: TRUE
        keep_md: TRUE
---

## Testis 4

Here I explore clustering using Seurat v2 for clustering.

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    warning = FALSE,
    message = FALSE,
    include = TRUE,
    echo = FALSE,
    cache.lazy = FALSE,
    fig.path = "testis4_figures/",
    fig.ext = c("png", "svg"),
    fig.width = 8
)
```

```{r load_libraries}
library(Seurat)
library(dplyr)
library(ggplot2)
set.seed(42)
```

```{r globals}
SAMPLE <- "testis4"
RESOLUTIONS <- c(0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 1.1, 1.2)
SEL_RESOLUTION <- "res.0.6"
PCA_DIMS <- 1:10

PROJ_DIR <- "/home/fearjm/Projects/larval_gonad"
DATA_DIR <- file.path(PROJ_DIR, paste0("output/cellselection-wf/", SAMPLE))
OUTDIR <- file.path(PROJ_DIR, "output/seurat2-cluster-wf")

GENE_ANNOTATION <- file.path(PROJ_DIR, "references/gene_annotation_dmel_r6-26.feather")
LITERATURE_GENES <- file.path(PROJ_DIR, "config/literature_genes.yaml")
```

```{r load_gene_annotations}
fbgn2symbol <- feather::read_feather(
    GENE_ANNOTATION,
    columns = c("FBgn", "gene_symbol")
)
```

```{r load_10x_data}
tenx <- Read10X(data.dir = DATA_DIR)
sobj <- CreateSeuratObject(
    raw.data = tenx,
    min.cells = 3,
    project = SAMPLE
)
```

### Normalize Data

```{r normalize, include=TRUE}
sobj <- NormalizeData(
    sobj,
    normalization.method = "LogNormalize",
    scale.factor = 1e4,
    display.progress = FALSE
)
```

```{r find_variable_genes, fig.width=8, fig.height=5, echo=TRUE}
sobj <- FindVariableGenes(
    sobj,
    mean.function = ExpMean,
    dispersion.function = LogVMR,
    x.low.cutoff = 0.0125,
    x.high.cutoff = 3,
    y.cutoff = 0.5,
    display.progress = FALSE
)
```

### Scale Data

```{r scale_data, echo=TRUE}
sobj <- ScaleData(
    sobj,
    vars.to.regress = "nUMI",
    display.progress = FALSE
)
```

### Dimensionality Reduction

```{r dim_reduction}
sobj <- RunPCA(
    sobj,
    pc.genes = sobj@var.genes,
    do.print = FALSE
)

sobj <- ProjectPCA(
    sobj,
    do.print = FALSE
)
```

#### Dimensional Gene Loadings

```{r dotplot_pcs, fig.wdith=8, fig.height=12}
VizPCA(sobj, pcs.use = 1:4)
```

#### Top Genes Heatmap

```{r heatmap_pca, fig.width=8, fig.height=20}
PCHeatmap(sobj, pc.use = 1:15, do.balanced = TRUE, label.columns = FALSE)
```

#### JackStraw

```{r run_jackstraw}
sobj <- JackStraw(
    sobj,
    num.replicate = 100,
    num.pc = 20,
    do.par = TRUE,
    num.cores = 4,
    display.progress = FALSE
)
```

```{r jackstraw_pca, fig.width=8, fig.height=12}
JackStrawPlot(sobj, PCs = 1:20, nCol = 4)
```

#### Elbow Plot

```{r elbow_pca}
PCElbowPlot(sobj)
```

#### Dimension Selection


### Clustering

```{r run_clustering}
sobj <- FindClusters(
    sobj,
    reduction.type = "pca",
    resolution = RESOLUTIONS,
    dims.use = PCA_DIMS,
    save.SNN = FALSE,
    print.output = FALSE
)

diff_res <- sobj@meta.data %>% select(contains("res"))
for (i in 1:dim(diff_res)[[2]]) {
    res <- diff_res[, i]
    name <- colnames(diff_res)[[i]]
    lvls <- unique(res)
    print(paste0(name, ":  ", length(lvls)))
}

sobj <- SetAllIdent(sobj, id = SEL_RESOLUTION)
```

```{r umap, fig.asp=1}
sobj <- RunUMAP(
    sobj,
    reduction.use = "pca",
    dims.use = PCA_DIMS,
    min_dist = 0.75
)

p1 <- DimPlot(
    sobj,
    reduction.use = "umap",
    do.return = TRUE
) +
    ggtitle(paste0(SAMPLE, ": ", SEL_RESOLUTION))
print(p1)
```

```{r tsne, fig.asp=1}
sobj <- RunTSNE(
    sobj,
    reduction.use = "pca",
    dims.use = PCA_DIMS,
    save.SNN = FALSE,
    print.output = FALSE
)

p1 <- DimPlot(
    sobj,
    reduction.use = "tsne",
    do.return = TRUE
) +
    ggtitle(paste0(SAMPLE, ": ", SEL_RESOLUTION))

print(p1)
```

### Look at marker genes

```{r load_lit_genes}
lit_genes <- yaml::yaml.load_file(LITERATURE_GENES)
```

#### Spermatogonia

```{r heatmap_gonia, fig.width=8, fig.height=16}
lg <- fbgn2symbol %>%
    filter(FBgn %in% lit_genes[["gonia"]]) %>%
    pull("gene_symbol")

VlnPlot(sobj, features.plot = lg, use.raw = TRUE, point.size.use = .1, nCol = 3)

FeaturePlot(
    sobj,
    features.plot = lg,
    reduction.use = "tsne",
    cols.use = c("gray", "purple"),
    pt.size = .3,
    nCol = 3
)
```

#### Spermatocytes

```{r heatmap_spermatocytes, fig.width=8, fig.height=16}
lg <- fbgn2symbol %>%
    filter(FBgn %in% lit_genes[["spermatocytes"]]) %>%
    pull("gene_symbol")

VlnPlot(sobj, features.plot = lg, use.raw = TRUE, point.size.use = .1, nCol = 3)

FeaturePlot(
    sobj,
    features.plot = lg,
    reduction.use = "tsne",
    cols.use = c("gray", "purple"),
    pt.size = .3,
    nCol = 3
)
```

#### CySC

```{r heatmap_cysc, fig.width=8, fig.height=16}
lg <- fbgn2symbol %>%
    filter(FBgn %in% lit_genes[["cysc"]]) %>%
    pull("gene_symbol")

VlnPlot(sobj, features.plot = lg, use.raw = TRUE, point.size.use = .1, nCol = 3)

FeaturePlot(
    sobj,
    features.plot = lg,
    reduction.use = "tsne",
    cols.use = c("gray", "purple"),
    pt.size = .3,
    nCol = 3
)
```

#### TE

```{r heatmap_te, fig.width=8, fig.height=9}
lg <- fbgn2symbol %>%
    filter(FBgn %in% lit_genes[["te"]]) %>%
    pull("gene_symbol")

VlnPlot(sobj, features.plot = lg, use.raw = TRUE, point.size.use = .1, nCol = 3)

FeaturePlot(
    sobj,
    features.plot = lg,
    reduction.use = "tsne",
    cols.use = c("gray", "purple"),
    pt.size = .3,
    nCol = 3
)
```

#### PC

```{r heatmap_pc, fig.width=8, fig.height=4}
lg <- fbgn2symbol %>%
    filter(FBgn %in% lit_genes[["pigment"]]) %>%
    pull("gene_symbol")

VlnPlot(sobj, features.plot = lg, use.raw = TRUE, point.size.use = .1)

FeaturePlot(
    sobj,
    features.plot = lg,
    reduction.use = "tsne",
    cols.use = c("gray", "purple"),
    pt.size = 1,
    nCol = 3
)
```

#### hub

```{r heatmap_hub, fig.width=8, fig.height=10}
lg <- fbgn2symbol %>%
    filter(FBgn %in% lit_genes[["hub"]]) %>%
    pull("gene_symbol")

VlnPlot(sobj, features.plot = lg, use.raw = TRUE, point.size.use = .1, nCol = 2)

FeaturePlot(
    sobj,
    features.plot = lg,
    reduction.use = "tsne",
    cols.use = c("gray", "purple"),
    pt.size = 1,
    nCol = 2
)
```

### Cluster Markers

```{r find_markers}
biomarkers <- FindAllMarkers(
    sobj,
    only.pos = TRUE,
    min.pct = 0.25,
    thres.use = 0.25,
    print.bar = FALSE
)

biomarkers <- tibble::as_tibble(biomarkers) %>%
    rename(gene_symbol = gene) %>%
    left_join(fbgn2symbol) %>%
    select(FBgn, gene_symbol, cluster, everything())
```

```{r num_markers_per_cluster}
biomarkers %>%
    filter(p_val_adj <= 0.001) %>%
    group_by(cluster) %>%
    summarise(num_markers_per_cluster = n()) %>%
    print(n = nrow(.))
```

#### Top 12 Genes Per Cluster

```{r top_markers}
top_markers <- biomarkers %>%
    filter(p_val_adj <= 0.001) %>%
    group_by(cluster) %>%
    top_n(n = 12, wt = avg_logFC)
```

```{r plot_top_markers, fig.width=20, fig.height=20}
for (i in 1:length(levels(biomarkers$cluster))) {
    clus <- levels(biomarkers$cluster)[[i]]
    features <- top_markers %>%
        filter(cluster == clus) %>%
        pull(gene_symbol)

    FeaturePlot(
        sobj,
        features.plot = features,
        reduction.use = "tsne",
        cols.use = c("gray", "purple"),
        pt.size = 1
    )
}
```

```{r save_biomarkers}
write.table(biomarkers,
    file = file.path(OUTDIR, paste(SAMPLE, "biomarkers.tsv", sep = "_")),
    sep = "\t",
    quote = FALSE,
    row.names = FALSE,
    col.names = TRUE
)

feather::write_feather(biomarkers,
    path = file.path(OUTDIR, paste(SAMPLE, "biomarkers.feather", sep = "_"))
)
```

```{r save_robj}
save(
    tesits1 = sobj,
    file = file.path(OUTDIR, paste(SAMPLE, "Robj", sep = "."))
)
```

```{r metadata}
df <- tibble::as_tibble(
    sobj@meta.data %>%
        tibble::rownames_to_column("cell_id")
)

df$clusters <- df[, SEL_RESOLUTION] %>% pull(.)

write.table(
    df,
    file = file.path(OUTDIR, paste(SAMPLE, "clusters.tsv", sep = "_")),
    sep = "\t",
    quote = FALSE,
    row.names = FALSE,
    col.names = TRUE
)

feather::write_feather(df,
    path = file.path(OUTDIR, paste(SAMPLE, "clusters.feather", sep = "_"))
)
```
