---
title: Seurat3 Integrate Testis Replicates (n = 3)
author: Justin Fear
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
output: 
    html_document:
        self_contained: TRUE
        keep_md: TRUE
---

## Replicate Integration (Seurat v3; n = 3)

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    warning = FALSE,
    message = FALSE,
    include = TRUE,
    echo = FALSE,
    cache.lazy = FALSE,
    fig.path = "combined_n3_figures/",
    dev = c("png", "svg"),
    fig.width = 8
)
```

```{r load_libraries}
library(Seurat)
library(dplyr)
library(ggplot2)
library(cowplot)
set.seed(42)
```

```{r globals}
SAMPLES <- c("testis1", "testis2", "testis3")
RESOLUTIONS <- c(0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 1.1, 1.2)
SEL_RESOLUTION <- "integrated_snn_res.0.3"
PCA_DIMS <- 1:9

PROJ_DIR <- "/home/fearjm/Projects/larval_gonad"
DATA_DIR <- file.path(PROJ_DIR, "output/seurat3-cluster-wf")

GENE_ANNOTATION <- file.path(PROJ_DIR, "references/gene_annotation_dmel_r6-26.feather")
LITERATURE_GENES <- file.path(PROJ_DIR, "config/literature_genes.yaml")
```

```{r load_gene_annotations}
fbgn2symbol <- feather::read_feather(
    GENE_ANNOTATION,
    columns = c("FBgn", "gene_symbol")
)
```

### Load Seurat Data Objects for Each Sample

```{r load_data}
load_seurat_data <- function(sample){
    load(file.path(DATA_DIR, paste0(sample, ".Robj")))

    sobj <- NormalizeData(sobj, verbose = FALSE)

    sobj <- FindVariableFeatures(
        sobj,
        selection.method = "vst",
        nfeatures = 2000,
        verbose = FALSE
    )

    sobj$sample <- sample
    return(sobj)
}

sample.list <- lapply(SAMPLES, load_seurat_data)
```

```{r dimplots, fig.width=8, fig.height=12}
plts <- lapply(sample.list, DimPlot, label = TRUE, legend = "none")
gridExtra::grid.arrange(grobs = plts)
```

```{r find_anchors}
anchors <- FindIntegrationAnchors(sample.list, dims = 1:30)
```

```{r combine_samples}
combined <- IntegrateData(anchorset = anchors, dims = 1:30)
DefaultAssay(combined) <- "integrated"
```


```{r scale_dimension_reduction}
combined <- ScaleData(combined, verbose = FALSE)

combined <- RunPCA(
    combined,
    npcs = 30,
    features = VariableFeatures(combined),
    verbose = FALSE
)

combined <- RunUMAP(combined, reduction = "pca", dims = PCA_DIMS)
```

```{r find_clusters}
combined <- FindNeighbors(
    combined,
    reduction = "pca",
    dims = PCA_DIMS,
    verbose = FALSE
)

combined <- FindClusters(combined, resolution = RESOLUTIONS, verbose = FALSE)
```

```{r umap_reps, fig.width=8, fig.height=4}
combined <- SetIdent(combined, value = SEL_RESOLUTION)
p1 <- DimPlot(combined, reduction = "umap", group.by = "sample")
p2 <- DimPlot(combined, reduction = "umap", label = TRUE)
plot_grid(p1, p2)
```

```{r umap_reps_split, fig.width=8, fig.height=4}
DimPlot(combined, reduction = "umap", split.by = "sample")
```

```{r num_cells_per_cluster}
combined[[c("sample", SEL_RESOLUTION)]] %>%
    rename(res = SEL_RESOLUTION) %>%
    group_by(res) %>%
    summarise(num_cells = n())
```

```{r num_cells_per_rep_per_cluster}
combined[[c("sample", SEL_RESOLUTION)]] %>%
    rename(res = SEL_RESOLUTION) %>%
    group_by(sample, res) %>%
    summarise(num_cells = n()) %>%
    arrange(res, sample)
```

### Look at marker genes

```{r load_lit_genes}
lit_genes <- yaml::yaml.load_file(LITERATURE_GENES)
```

#### Spermatogonia

```{r heatmap_gonia, fig.width=8, fig.height=20}
lg <- fbgn2symbol %>%
    filter(FBgn %in% lit_genes[["gonia"]]) %>%
    pull("gene_symbol")

VlnPlot(combined, features = lg, ncol = 2, pt.size = .1)
FeaturePlot(
    combined,
    features = lg,
    ncol = 2,
    pt.size = .4,
    min.cutoff = 0,
    order = TRUE
)
```

```{r vas_bam, fig.width=8, fig.height=4}
FeaturePlot(
    combined,
    features = c("vas", "bam"),
    pt.size = .4,
    min.cutoff = 0,
    order = TRUE
)
```

#### Spermatocytes

```{r heatmap_spermatocytes, fig.width=8, fig.height=28}
lg <- fbgn2symbol %>%
    filter(FBgn %in% lit_genes[["spermatocytes"]]) %>%
    pull("gene_symbol")

VlnPlot(combined, features = lg, ncol = 2, pt.size = .1)
FeaturePlot(
    combined,
    features = lg,
    ncol = 2,
    pt.size = .4,
    min.cutoff = 0,
    order = TRUE
)
```

```{r aly_nht_can_soti, fig.width=8, fig.height=8}
FeaturePlot(
    combined,
    features = c("aly", "can", "nht", "soti"),
    ncol = 2,
    pt.size = .4,
    min.cutoff = 0,
    order = TRUE
)
```

#### CySC

```{r heatmap_cysc, fig.width=8, fig.height=30}
lg <- fbgn2symbol %>%
    filter(FBgn %in% lit_genes[["cysc"]]) %>%
    pull("gene_symbol")

VlnPlot(combined, features = lg, ncol = 2, pt.size = .1)
FeaturePlot(
    combined,
    features = lg,
    ncol = 2,
    pt.size = .4,
    min.cutoff = 0,
    order = TRUE
)
```

```{r tj_eya, fig.width=8, fig.height=4}
FeaturePlot(combined, features = c("tj", "eya"), pt.size = .4, min.cutoff = 0, order=TRUE)
FeaturePlot(
    combined,
    features = c("tj", "eya"),
    ncol = 2,
    pt.size = .4,
    min.cutoff = 0,
    order = TRUE
)
```

#### TE

```{r heatmap_te, fig.width=8, fig.height=12}
lg <- fbgn2symbol %>%
    filter(FBgn %in% lit_genes[["te"]]) %>%
    pull("gene_symbol")

VlnPlot(combined, features = lg, ncol = 2, pt.size = .1)
FeaturePlot(
    combined,
    features = lg,
    ncol = 2,
    pt.size = .4,
    min.cutoff = 0,
    order = TRUE
)
```

#### PC

```{r heatmap_pc, fig.width=8, fig.height=4}
lg <- fbgn2symbol %>%
    filter(FBgn %in% lit_genes[["pigment"]]) %>%
    pull("gene_symbol")

VlnPlot(combined, features = lg, pt.size = .1)
FeaturePlot(
    combined,
    features = lg,
    ncol = 2,
    pt.size = .4,
    min.cutoff = 0,
    order = TRUE
)
```

#### hub

```{r heatmap_hub, fig.width=8, fig.height=10}
lg <- fbgn2symbol %>%
    filter(FBgn %in% lit_genes[["hub"]]) %>%
    pull("gene_symbol")

VlnPlot(combined, features = lg, ncol = 2, pt.size = .1)
FeaturePlot(
    combined,
    features = lg,
    ncol = 2,
    pt.size = .4,
    min.cutoff = 0,
    order = TRUE
)
```


```{r save_robj}
save(
    tesits1 = combined,
    file = file.path(
        DATA_DIR,
        paste0(
            paste("combined", paste0("n", length(SAMPLES)), sep = "_"),
            ".Robj"
        )
    )
)
```