---
title: GO Analysis Combined (n=3)
author: Justin M. Fear
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
output: 
    html_document:
        self_contained: TRUE
        keep_md: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    warning = FALSE,
    message = FALSE,
    include = TRUE,
    echo = FALSE,
    cache.lazy = FALSE,
    fig.path = "combined_n3_GO_figures/",
    dev = c("png", "svg"),
    fig.width = 8
)
```
```{r globals}
PROJ_DIR <- "/home/fearjm/Projects/larval_gonad"
```

```{r load_library}
library(feather)
library(dplyr)
library(clusterProfiler)
```

```{r helper_function}
gogo <- function(clus, df, bg) {
    genes <- df %>%
        filter(cluster == clus) %>%
        dplyr::select(FBgn) %>%
        pull(.)

    res <- enrichGO(
        genes,
        OrgDb = "org.Dm.eg.db",
        keyType = "FLYBASE",
        ont = "BP",
        universe = bg,
        pAdjustMethod = "BH",
        qvalueCutoff = .01
    )

    return(res)
}
```

```{r load_biomarkers}
biomarkers <- read_feather("combined_n3_biomarkers.feather") %>% filter(p_val_adj <= 0.001)
```

```{r background}
background <- read_feather("combined_n3_normalized.feather") %>% pull(FBgn)
```

```{r lit_genes, echo=TRUE}
lit_genes <- yaml::yaml.load_file(file.path(PROJ_DIR, "config/literature_genes.yaml"))
```

## Spermatogonia (G)

### Biolgoical Process
```{r g, fig.width=10, fig.height=10}
res <- gogo("6", biomarkers, background)
dotplot(res, showCategory = 20)
```

```{r pct_lit_sp, echo=TRUE}
gl <- lit_genes[["SP"]]
print(sum(gl %in% res@gene) / length(gl))
```

## Early Primary Spermatocytes (EPS)

### Biolgoical Process
```{r eps, fig.width=10, fig.height=10}
res <- gogo("4", biomarkers, background)
dotplot(res, showCategory = 20)
```

```{r pct_lit_eps, echo=TRUE}
gl <- c(lit_genes[["G_EPS"]], lit_genes[["EPS"]])
print(sum(gl %in% res@gene) / length(gl))
```

## Primary Spermatocytes 

### Biolgoical Process (MPS)
```{r mps, fig.width=10, fig.height=10}
res <- gogo("0", biomarkers, background)
dotplot(res, showCategory = 20)
```

```{r pct_lit_ps1, echo=TRUE}
gl <- c(lit_genes[["EPS_MPS_LPS"]], lit_genes[["G_EPS_MPS_LPS"]])
print(sum(gl %in% res@gene) / length(gl))
```

### Biolgoical Process (LPS)
```{r lps, fig.width=10, fig.height=10}
res <- gogo("2", biomarkers, background)
dotplot(res, showCategory = 20)
```

```{r pct_lit_ps2, echo=TRUE}
gl <- c(lit_genes[["EPS_MPS_LPS"]], lit_genes[["G_EPS_MPS_LPS"]])
print(sum(gl %in% res@gene) / length(gl))
```

## Cyst Cells

### Biolgoical Process (C1)
```{r c1, fig.width=10, fig.height=10}
res <- gogo("1", biomarkers, background)
dotplot(res, showCategory = 20)
```

```{r pct_lit_c1, echo=TRUE}
gl <- lit_genes[["cyst"]]
print(sum(gl %in% res@gene) / length(gl))
```

### Biolgoical Process (C2)
```{r c2, fig.width=10, fig.height=10}
res <- gogo("5", biomarkers, background)
dotplot(res, showCategory = 20)
```

```{r pct_lit_c2, echo=TRUE}
gl <- lit_genes[["cyst"]]
print(sum(gl %in% res@gene) / length(gl))
```

### Biolgoical Process (C3)
```{r c3, fig.width=10, fig.height=10}
res <- gogo("8", biomarkers, background)
dotplot(res, showCategory = 20)
```

```{r pct_lit_c3, echo=TRUE}
gl <- lit_genes[["cyst"]]
print(sum(gl %in% res@gene) / length(gl))
```

### Biolgoical Process (C4)
```{r c4, fig.width=10, fig.height=10}
res <- gogo("7", biomarkers, background)
dotplot(res, showCategory = 20)
```

```{r pct_lit_c4, echo=TRUE}
gl <- lit_genes[["cyst"]]
print(sum(gl %in% res@gene) / length(gl))
```

## Terminal Epithelium (T)

### Biolgoical Process
```{r te, fig.width=10, fig.height=10}
res <- gogo("3", biomarkers, background)
dotplot(res, showCategory = 20)
```

```{r pct_lit_te, echo=TRUE}
gl <- lit_genes[["T"]]
print(sum(gl %in% res@gene) / length(gl))
```

## Pigment Cells (P)

### Biolgoical Process
```{r pc, fig.width=10, fig.height=10}
res <- gogo("9", biomarkers, background)
dotplot(res, showCategory = 20)
```

```{r pct_lit_pc, echo=TRUE}
gl <- lit_genes[["P"]]
print(sum(gl %in% res@gene) / length(gl))
```
