---
title: Seurat3 Integrate Testis Replicates
author: Justin Fear
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
output: 
    html_document:
        self_contained: TRUE
        keep_md: TRUE
---

## Replicate Integration (Seurat v3)

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    warning = FALSE,
    message = FALSE,
    include = TRUE,
    echo = FALSE,
    cache.lazy = FALSE,
    fig.path = "integrated_figures/",
    fig.ext = c("png", "svg"),
    fig.width = 8
)
```

```{r load_libraries}
library(Seurat)
library(dplyr)
library(ggplot2)
set.seed(42)
```

```{r globals}
SAMPLES <- c("testis1", "testis2", "testis3", "testis4")
RESOLUTIONS <- c(0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 1.1, 1.2)
SEL_RESOLUTION <- "RNA_snn_res.0.8"
PCA_DIMS <- 1:9

PROJ_DIR <- "/Users/fearjm/Projects/larval_gonad"
DATA_DIR <- file.path(PROJ_DIR, "output/seurat3-cluster-wf")

GENE_ANNOTATION <- file.path(PROJ_DIR, "references/gene_annotation_dmel_r6-24.feather")
LITERATURE_GENES <- file.path(PROJ_DIR, "config/literature_genes.yaml")
```

```{r load_gene_annotations}
fbgn2symbol <- feather::read_feather(
    GENE_ANNOTATION,
    columns = c("FBgn", "gene_symbol")
)
```

### Load Seurat Data Objects for Each Sample

```{r load_data}
load_seurat_data <- function(sample){
    load(file.path(DATA_DIR, paste0(sample, '.Robj')))
    sobj <- NormalizeData(sobj, verbose = FALSE)
    sobj <- FindVariableFeatures(sobj, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
    sobj$sample <- sample
    return(sobj)
}

sample.list <- lapply(SAMPLES, load_seurat_data)
```

```{r dimplots, fig.width=12, fig.height=10}
plts <- lapply(sample.list, DimPlot, label=TRUE, legend='none')
gridExtra::grid.arrange(grobs = plts)
```


```{r}
anchors <- FindIntegrationAnchors(sample.list, dims=1:30)
```




