---
title: Seurat Cluster Individual Sample
author: Justin Fear
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse=TRUE, warning=FALSE, message=FALSE, cache.lazy=FALSE,
                      bootstrap.show.code=FALSE, bootstrap.show.output=FALSE,
                      fig.ext='png')
```

```{r set_globals_snakemake, include=FALSE, eval=TRUE}
SAMPLE <- snakemake@wildcards[['sample']]
DATA_DIR <- file.path('../', dirname(snakemake@input[["data"]]))
FBGN2CHROM <- file.path('../', snakemake@input[['fbgn2chrom']])
OUTDIR <- file.path('../', dirname(snakemake@output[[1]]))
REP <- snakemake@params[['rep']]
RESOLUTIONS <- snakemake@params[['resolutions']]

GENE_LOW <- snakemake@params[['gene_low']]
if (GENE_LOW == 'None'){
  GENE_LOW = -Inf
} else {
  GENE_LOW = as.numeric(GENE_LOW)
}

GENE_HIGH <- snakemake@params[['gene_high']]
if (GENE_HIGH == 'None'){
  GENE_HIGH = Inf
} else {
  GENE_HIGH = as.numeric(GENE_HIGH)
}

UMI_LOW <- snakemake@params[['umi_low']]
if (UMI_LOW == 'None'){
  UMI_LOW = -Inf
} else {
  UMI_LOW = as.numeric(UMI_LOW)
}

UMI_HIGH <- snakemake@params[['umi_high']]
if (UMI_HIGH == 'None'){
  UMI_HIGH = Inf
} else {
  UMI_HIGH = as.numeric(UMI_HIGH)
}
```

```{r set_other_globas}
REFERENCES_DIR <- Sys.getenv('REFERENCES_DIR', '/data/LCDB/lcdb-references')
```

## `r SAMPLE`
* Gene Low End Cutoff: `r GENE_LOW`
* Gene High End Cutoff: `r GENE_HIGH`
* UMI Low End Cutoff: `r UMI_LOW`
* UMI High End Cutoff: `r UMI_HIGH`

```{r load_libraries, include=FALSE}
options(repr.plot.width=10, repr.plot.height=10)
source('../../lib/seurat.R')
library(Seurat)
library(dplyr)
library(Matrix)
library(data.table)
library(yaml)
```

```{r import_annotations}
fbgn2chrom <- read.table(FBGN2CHROM, header=T)

# Get list of mitochondiral genes
mito <- fbgn2chrom[fbgn2chrom$chrom == 'chrM', 'FBgn']
print(length(mito))
```

### Load 10X Data

```{r load_10x_data}
tenX.data <- Read10X(data.dir = DATA_DIR)
colnames(tenX.data) <- paste(REP, colnames(tenX.data), sep = "_")
sobj <- CreateSeuratObject(
    raw.data = tenX.data,
    min.cells = 3,
    min.genes = 200,
    project = 'GroupCluster',
    display.progress = FALSE
)
sobj@meta.data$rep <- REP
remove(tenX.data)
```

```{r plot_gene_and_umi, fig.width = 8}
VlnPlot(
    object = sobj,
    features.plot = c("nGene", "nUMI"),
    nCol = 2
)
```

```{r filter_cells}
# Filter based on the number of genes
sobj <- FilterCells(
    object = sobj,
    subset.names = "nGene",
    low.thresholds = GENE_LOW,
    high.thresholds = GENE_HIGH
)

# Filter based on the total UMI
sobj <- FilterCells(
    object = sobj,
    subset.names = "nUMI",
    low.thresholds = UMI_LOW,
    high.thresholds = UMI_HIGH
)
```

### Normalization and Dimension Reduction

```{r normalize}
sobj <- NormalizeData(
    object = sobj,
    normalization.method = "LogNormalize",
    scale.factor = 1e4,
    display.progress = FALSE
)
```

```{r find_variable_genes}
sobj <- FindVariableGenes(
    object = sobj,
    do.plot = TRUE,
    display.progress = FALSE
)
```

```{r scale_data_by_umi}
sobj <- ScaleData(
    object = sobj,
    vars.to.regress = "nUMI",
    display.progress = FALSE
)
```

```{r dim_reduce}
sobj <- RunPCA(
    object = sobj, 
    pc.genes = sobj@var.genes, 
    do.print = FALSE 
)

# Project other genes onto the PCA components
sobj <- ProjectPCA(object = sobj, do.print = FALSE)
```

```{r plot_pca, fig.width=8}
p1 <- PCAPlot(object = sobj, dim.1 = 1, dim.2 = 2, do.return = T)
p2 <- PCAPlot(object = sobj, dim.1 = 1, dim.2 = 3, do.return = T)
p3 <- PCAPlot(object = sobj, dim.1 = 2, dim.2 = 3, do.return = T)
plot_grid(p1, p2, p3)
PCElbowPlot(object = sobj)
```

### Clustering 

```{r find_clusters}
sobj <- FindClusters(
    object = sobj, 
    reduction.type = "pca", 
    resolution = RESOLUTIONS, 
    dims.use = 1:8, 
    save.SNN = FALSE, 
    print.output = FALSE
)
```

```{r run_tsne}
sobj <- RunTSNE(sobj, reduction.use = "pca", dims.use = 1:8, do.fast = TRUE)
```

```{r plot_tsne_results, fig.width=8}
for (i in RESOLUTIONS){
  name <- paste0('res.', i)
  sobj <- SetAllIdent(sobj, id = name)
  
  p1 <- TSNEPlot(sobj, do.return = T, pt.size = 0.5, group.by = "rep")
  p2 <- TSNEPlot(sobj, do.label = T, do.return = T, pt.size = 0.5)
  p <- plot_grid(p1, p2)
  
  title <- ggdraw() + draw_label(name, fontface='bold')
  print(plot_grid(title, p, ncol=1, rel_heights=c(0.1, 1))) # rel_heights values control title margins
}
```


### Look at marker genes
```{r load_lit_genes}
lit_genes = yaml.load_file('../../config/literature_genes.yaml')
```

#### Spermatogonia
```{r plot_heatmap_gonia, fig.width=20, fig.height=20}
VlnPlot(object = sobj, features.plot = lit_genes[['gonia']], use.raw = TRUE, y.log = TRUE)
FeaturePlot(sobj, lit_genes[['gonia']], reduction.use = 'tsne', cols.use = c('gray', 'purple'))
```

#### Spermatocytes
```{r plot_heatmap_spermatocytes, fig.width=20, fig.height=20}
VlnPlot(object = sobj, features.plot = lit_genes[['spermatocytes']], use.raw = TRUE, y.log = TRUE)
FeaturePlot(sobj, lit_genes[['spermatocytes']], reduction.use = 'tsne', cols.use = c('gray', 'purple'))
```

#### CySC
```{r plot_heatmap_cysc, fig.width=20, fig.height=20}
VlnPlot(object = sobj, features.plot = lit_genes[['cysc']], use.raw = TRUE, y.log = TRUE)
FeaturePlot(sobj, lit_genes[['cysc']], reduction.use = 'tsne', cols.use = c('gray', 'purple'))
```

#### TE
```{r plot_heatmap_te, fig.width=20, fig.height=20}
VlnPlot(object = sobj, features.plot = lit_genes[['te']], use.raw = TRUE, y.log = TRUE)
FeaturePlot(sobj, lit_genes[['te']], reduction.use = 'tsne', cols.use = c('gray', 'purple'))
```

#### PC
```{r plot_heatmap_pc, fig.width=20}
VlnPlot(object = sobj, features.plot = lit_genes[['pigment']], use.raw = TRUE, y.log = TRUE)
FeaturePlot(sobj, lit_genes[['pigment']], reduction.use = 'tsne', cols.use = c('gray', 'purple'))
```

#### hub
```{r plot_heatmap_hub, fig.width=20, fig.height=20}
VlnPlot(object = sobj, features.plot = lit_genes[['hub']], use.raw = TRUE, y.log = TRUE)
FeaturePlot(sobj, lit_genes[['hub']], reduction.use = 'tsne', cols.use = c('gray', 'purple'))
```

### Save Results
```{r dump_seurat}
save(object = sobj, file = file.path(OUTDIR, "seurat.Robj"))
```