"""Common elements used for the scRNA-Seq data.

This is a place to store functions and variables that are used over and over
again with the scRNA-seq data.

"""

CLUSTER_ANNOT = {
    0: 'Late 1º Spermatocytes (0)',
    1: 'Mid Cyst Cells (1)',
    2: 'Mid 1º Spermatocytes (2)',
    3: 'Early 1º Spermatocytes (3)',
    4: 'Late Cyst Cells (4)',
    5: 'Early Cyst Cells (5)',
    6: 'Spermatogonia (6)',
    7: 'Terminal Epithelium (7)',
    8: 'Pigment Cells (8)',
    9: 'Unknown (9)',
    10: 'Unknown (10)',
    11: 'Unknown (11)',
}

CLUSTER_ORDER = [
    'Spermatogonia (6)',
    'Early 1º Spermatocytes (3)',
    'Mid 1º Spermatocytes (2)',
    'Late 1º Spermatocytes (0)',
    'Early Cyst Cells (5)',
    'Mid Cyst Cells (1)',
    'Late Cyst Cells (4)',
    'Terminal Epithelium (7)',
    'Pigment Cells (8)',
    'Unknown (9)',
    'Unknown (10)',
    'Unknown (11)',
]


# CLUSTER_ANNOT = {
#     0: 'Late Primary Spermatocytes (0)',
#     1: 'Early Somatic Cyst Cells (1)',
#     2: 'Late Somatic Cyst Cells (2)',
#     3: 'Late Somatic Cyst Cells (3)',
#     4: 'Spermatogonia (4)',
#     5: 'Terminal Epithelium (5)',
#     6: 'Mid Primary Spermatocytes (6)',
#     7: 'Late Somatic Cyst Cells (7)',
#     8: 'Early Primary Spermatocytes (8)',
#     9: 'Pigment Cells (9)',
#     10: 'Early Somatic Cyst Cells (10)',
#     11: 'Unknown (11)',
# }
#
# CLUSTER_ORDER = [
#     'Spermatogonia (4)',
#     'Early Primary Spermatocytes (8)',
#     'Mid Primary Spermatocytes (6)',
#     'Late Primary Spermatocytes (0)',
#     'Early Somatic Cyst Cells (1)',
#     'Early Somatic Cyst Cells (10)',
#     'Late Somatic Cyst Cells (2)',
#     'Late Somatic Cyst Cells (3)',
#     'Late Somatic Cyst Cells (7)',
#     'Terminal Epithelium (5)',
#     'Pigment Cells (9)',
#     'Unknown (11)',
# ]

# List of T2A Gal4 lines we have looked at.
T2A = [
    'vari',
    'CG42458',
    'CG34383',
    'CG34394',
    'CG7255',
    'Wnt4',
    'cv-2',
    'Eaf',
    'tun',
    'Zasp52',
    'Su(var)2-10',
    'GEFmeso',
    'ths',
    'pk',
    'rdo',
    'bin3',
    'CG2082',
    'Khc-73',
    'FER',
    'CG31075',
    'QC',
    'dally',
    'CG11658',
    'PyK',
    'PH4alphaEFB',
    'RasGAP1',
    'Ino80',
]

# List of GAL4 lines we have looked at
GAL4 = [
    'CG11658',
    'Notum',
    'CadN ',
    'Tsp74F',
    'sano',
    'rau',
    'CG32354',
    'trn',
    'Irk1',
    'bnl',
    'hng3',
    'tkv',
    'CG34383',
    'CG34323',
    'qjt',
    'qin',
    'qin',
    'klu',
    'CR46216',
    'mael',
    'CG9272',
    'CR33319',
    'Grx1t',
    'CG43059',
    'CG6888',
    'CG4218',
    'CR44852',
    'CG31644',
    'bol',
    'svp',
    'svp',
    'CG4822',
    'Meltrin',
    'Fili',
    'Papss',
    'AdamTS-A',
    'cdi',
    'eya',
    'CG42673',
]

# List of Ben White's T2A gal4 that we have looked at.
WHITE = [
    'AkhR',
    'burs',
    'CG2187',
    'ChaT',
    'CrzR',
    'Dh31R',
    'EH',
    'EHR',
    'ETHR',
    'ETHR',
    'ETHRB',
    'GluRIIB',
    'HR46',
    'HR46',
    'LGR1',
    'pburs',
    'Proc',
    'ProcR',
    'rk',
]

# List of protein traps that Erika has looked at.
PTRAP = [
    'ADD1', 'Ance', 'bbg', 'bol', 'CadN', 'CG11044',
    'CG17349', 'CG17646', 'CG3277', 'CG42321', 'CG43088', 'CG43373',
    'CG6356', 'CG8036', 'CG8851', 'CG9747', 'cindr', 'Dek',
    'DIP-delta', 'dlp', 'dpr17', 'dpr3', 'dsx', 'Efa6',
    'egr', 'eIF5B', 'e(y)3', 'Fas3', 'foxo', 'fru',
    'Fs(2)Ket', 'hid', 'ImpL2', 'klu', 'LRP1', 'Mapmodulin',
    'mbl', 'Mi-2', 'NetA', 'NFAT', 'nkd', 'nord',
    'Nrg', 'osa', 'p130CAS', 'p53', 'Pdcd4', 'Pde11',
    'Piezo', 'ppan', 'Ptp4E', 'Pvr', 'Rab3', 'Reck',
    'Sap-r', 'sdk', 'Sox102F', 'spir', 'SRPK', 'stai',
    'stg', 'svp', 'Ten-a', 'Ten-m', 'Tep2', 'tok',
    'tutl', 'twin', 'Vha68-3', 'Wdr62', 'wnd',
]
