sampletable: "config/sampletable.tsv"

patterns: "config/rnaseq_patterns.yaml"

# Which key in the `references` dict below to use
organism: "dmel"

# If not specified here, use the environment variable REFERENCES_DIR.
# references_dir: "references_data"

aligner:
  index: "hisat2"
  tag: "r6-24_and_ercc"

rrna:
  index: "bowtie2"
  tag: "rRNA"

gtf:
  tag: "r6-24_and_ercc"

db:
  tag: "r6-24"

salmon:
  tag: "r6-24_transcriptome_updated"

fastq_screen:
  - label: rRNA
    organism: dmel
    tag: rRNA
  - label: PhiX
    organism: phix
    tag: default
  - label: Fly
    organism: dmel
    tag: r6-24
  - label: Mouse
    organism: mouse
    tag: gencode_m18
  - label: Human
    organism: human
    tag: gencode-v28
  - label: Yeast
    organism: sacCer
    tag: sacCer3
  - label: Wolbachia
    organism: wolbachia
    tag: default


# See the reference config files in the top level of the repo,
# include/reference_configs, for inspiration for more species.

include_references:
  - "reference_configs/PhiX.yaml"
  - "reference_configs/Drosophila_melanogaster.yaml"
  - "reference_configs/Mus_musculus.yaml"
  - "reference_configs/Homo_sapiens.yaml"
  - "reference_configs/Saccharomyces_cerevisiae.yaml"
  - "reference_configs/Wolbachia_endosymbiont_of_Drosophila_melanogaster.yaml"
