author: Justin M Fear
email: justin.m.fear@gmail.com
project: Larval Gonad
git: https://github.com/jfear/larval_gonad
#references_dir: <path to references> defaults to environmental variable
assembly: dmel
tag: r6-24
fliersprops:
  alpha: .1
cluster_annot:
  0: 'PS4'
  1: 'CY2'
  2: 'PS3'
  3: 'CY3'
  4: 'CY1'
  5: 'PS1'
  6: 'PS2'
  7: 'TE'
  8: 'PC'
  9: 'SP'
cluster_order:
  - 'SP'
  - 'PS1'
  - 'PS2'
  - 'PS3'
  - 'PS4'
  - 'CY1'
  - 'CY2'
  - 'CY3'
  - 'TE'
  - 'PC'
chrom_order:
  - chrX
  - chr2L
  - chr2R
  - chr3L
  - chr3R
  - chr4
  - chrY
