author: Justin M Fear
email: justin.m.fear@gmail.com
project: Larval Gonad
git: https://github.com/jfear/larval_gonad
#references_dir: <path to references> defaults to environmental variable
assembly: dmel
tag: r6-16
fliersprops:
  alpha: .1
formats:
  - png
  - pdf
styles:
  - notebook
  - paper
  - talk
resolution: 'res.0.6'
cluster_annot:
  0: 'Late 1º Spermatocytes'
  1: 'Mid Cyst Cells'
  2: 'Mid 1º Spermatocytes'
  3: 'Early 1º Spermatocytes'
  4: 'Late Cyst Cells'
  5: 'Early Cyst Cells'
  6: 'Spermatogonia'
  7: 'Terminal Epithelium'
  8: 'Pigment Cells'
  #  9: 'Unknown (9)'
  #  10: 'Unknown (10)'
  #  11: 'Unknown (11)'
cluster_order:
  - 'Spermatogonia'
  - 'Early 1º Spermatocytes'
  - 'Mid 1º Spermatocytes'
    #- 'Unknown (11)'
  - 'Late 1º Spermatocytes'
  - 'Early Cyst Cells'
  - 'Mid Cyst Cells'
  - 'Late Cyst Cells'
    #- 'Unknown (9)'
    #- 'Unknown (10)'
  - 'Terminal Epithelium'
  - 'Pigment Cells'
chrom_order:
  - chrX
  - chr2L
  - chr2R
  - chr3L
  - chr3R
  - chr4
  - chrY
