author: Justin M Fear
email: justin.m.fear@gmail.com
project: Larval Gonad
git: https://github.com/jfear/larval_gonad
#references_dir: <path to references> defaults to environmental variable
assembly: dmel
tag: r6-24
fliersprops:
  alpha: .1
cluster_annot:
  "0": 'PS3'
  "1": 'CY1'
  "2": 'PS2'
  "3": 'CY2'
  "4": 'ECY'
  "5": 'EPS'
  "6": 'PS1'
  "7": 'TE'
  "8": 'PC'
  "9": 'SP'
cluster_order:
  - 'SP'
  - 'EPS'
  - 'PS1'
  - 'PS2'
  - 'PS3'
  - 'ECY'
  - 'CY1'
  - 'CY2'
  - 'TE'
  - 'PC'
cluster_types:
  - 'germ'
  - 'germ'
  - 'germ'
  - 'germ'
  - 'germ'
  - 'soma'
  - 'soma'
  - 'soma'
  - 'soma'
  - 'soma'
chrom_order:
  - chrX
  - chr2L
  - chr2R
  - chr3L
  - chr3R
  - chr4
  - chrY
legend_names:
  - 'Spermatogonia'
  - 'Early Primary Spermatocyte'
  - 'Primary Spermatocyte (1)'
  - 'Primary Spermatocyte (2)'
  - 'Primary Spermatocyte (2)'
  - 'Early Somatic Cyst Cell'
  - 'Somatic Cyst Cell (1)'
  - 'Somatic Cyst Cell (2)'
  - 'Terminal Epithelium'
  - 'Pigment Cells'