author: Justin M Fear
email: justin.m.fear@gmail.com
project: Larval Gonad
git: https://github.com/jfear/larval_gonad
#references_dir: <path to references> defaults to environmental variable
assembly: dmel
tag: r6-24
fliersprops:
  alpha: .1
cluster_annot:
  "0": 'PS3'
  "1": 'CY1'
  "2": 'PS2'
  "3": 'CY2'
  "4": 'ECY'
  "5": 'EPS'
  "6": 'PS1'
  "7": 'TE'
  "8": 'PC'
  "9": 'SP'
cluster_order:
  - 'SP'
  - 'EPS'
  - 'PS1'
  - 'PS2'
  - 'PS3'
  - 'ECY'
  - 'CY1'
  - 'CY2'
  - 'TE'
  - 'PC'
chrom_order:
  - chrX
  - chr2L
  - chr2R
  - chr3L
  - chr3R
  - chr4
  - chrY
