author: Justin M Fear
email: justin.m.fear@gmail.com
project: Larval Gonad
git: https://github.com/jfear/larval_gonad
assembly: dmel
tag: r6-26
release_date: "2019_01"

fliersprops:
  alpha: .1

cluster_annot:
  "0": "MPS"
  "1": "C1"
  "2": "LPS"
  "3": "T"
  "4": "EPS"
  "5": "C2"
  "6": "G"
  "7": "C4"
  "8": "C3"
  "9": "P"

cluster_order:
  - "G"
  - "EPS"
  - "MPS"
  - "LPS"
  - "C1"
  - "C2"
  - "C3"
  - "C4"
  - "T"
  - "P"

legend_names:
  - "Spermatogonia (G)"
  - "Early Primary Spermatocyte (E1°)"
  - "Mid Primary Spermatocyte (M1°)"
  - "Later Primary Spermatocyte (L1°)"
  - "Cyst Cell (C1)"
  - "Cyst Cell (C2)"
  - "Cyst Cell (C3)"
  - "Cyst Cell (C4)"
  - "Terminal Epithelium (T)"
  - "Pigment Cells (P)"

cluster_types:
  - "germ"
  - "germ"
  - "germ"
  - "germ"
  - "soma"
  - "soma"
  - "soma"
  - "soma"
  - "soma"
  - "soma"

germ:
  - "G"
  - "EPS"
  - "MPS"
  - "LPS"

soma:
  - "C1"
  - "C2"
  - "C3"
  - "C4"
  - "T"
  - "P"

spermatocytes:
  - "EPS"
  - "MPS"
  - "LPS"

cyst:
  - "C1"
  - "C2"
  - "C3"
  - "C4"

chrom_order:
  - "X"
  - "2L"
  - "2R"
  - "3L"
  - "3R"
  - "4"
  - "Y"

autosomes:
  - "2L"
  - "2R"
  - "3L"
  - "3R"

gene_subsets:
  - "expressed"
  - "commonly_expressed"
  - "tau"
  - "tsps"
  - "male"
  - "female"
  - "sex_ns"
  - "testis"
  - "ovary"
  - "gonad_ns"
  - "male_soma"
  - "female_soma"
  - "sex_soma_ns"
  - "larval_testis"
  - "larval_ovary"
  - "larval_gonad_ns"
  - "G"
  - "LPS"

gene_subset_titles:
  expressed: "All Genes"
  commonly_expressed: "Commonly Expressed Genes"
  tau: "Housekeeping Genes (τ)"
  tsps: "Housekeeping Genes (TSPS)"
  male: "Male-Biased Expressed Genes"
  female: "Female-Biased Expressed Genes"
  sex_ns: "Non-Sex-Biased Expressed Genes"
  testis: "Testis-Biased Expressed Genes"
  ovary: "Ovary-Biased Expressed Genes"
  gonad_ns: "Non-Gonad-Biased Expressed Genes"
  male_soma: "Somatic Male-Biased Expressed Genes"
  female_soma: "Somatic Female-Biased Expressed Genes"
  sex_soma_ns: "Somatic Non-Sex-Biased Expressed Genes"
  larval_testis: "Larval Testis-Biased Expressed Genes"
  larval_ovary: "Larval Ovary-Biased Expressed Genes"
  larval_gonad_ns: "Larval Non-Gonad-Biased Expressed Genes"
  G: "G-Biased (G vs LPS)"
  LPS: "LPS-Biased (G vs LPS)"

deg_subsets:
  - "male"
  - "female"
  - "sex_ns"
  - "testis"
  - "ovary"
  - "gonad_ns"
  - "male_soma"
  - "female_soma"
  - "sex_soma_ns"
  - "larval_testis"
  - "larval_ovary"
  - "larval_gonad_ns"

ratio_types:
  - "x_to_a_ratio"
  - "fourth_to_a_ratio"
  - "y_to_a_ratio"