author: Justin M Fear
email: justin.m.fear@gmail.com
project: Larval Gonad
git: https://github.com/jfear/larval_gonad
#references_dir: <path to references> defaults to environmental variable
assembly: dmel
tag: r6-16
fliersprops:
  alpha: .1
formats:
  - png
  - pdf
styles:
  - notebook
  - paper
  - talk
resolution: 'res.0.6'
cluster_annot:
  0: 'Late 1º Spermatocytes'
  1: 'Mid Cyst Cells'
  2: 'Mid 1º Spermatocytes'
  3: 'Early 1º Spermatocytes'
  4: 'Late Cyst Cells'
  5: 'Early Cyst Cells'
  6: 'Spermatogonia'
  7: 'Terminal Epithelium'
  8: 'Pigment Cells'
  9: 'Unknown (9)'
  10: 'Unknown (10)'
  11: 'Unknown (11)'
short_cluster_annot:
  0: 'L1º'
  1: 'MC'
  2: 'M1º'
  3: 'E1º'
  4: 'LC'
  5: 'EC'
  6: 'SP'
  7: 'TE'
  8: 'PC'
  9: 'U1'
  10: 'U2'
  11: 'U3'
cluster_order:
  - 'Spermatogonia'
  - 'Early 1º Spermatocytes'
  - 'Mid 1º Spermatocytes'
  - 'Late 1º Spermatocytes'
  - 'Early Cyst Cells'
  - 'Mid Cyst Cells'
  - 'Late Cyst Cells'
  - 'Terminal Epithelium'
  - 'Pigment Cells'
  - 'Unknown (9)'
  - 'Unknown (10)'
  - 'Unknown (11)'
short_cluster_order:
  - 'SP'
  - 'E1º'
  - 'M1º'
  - 'L1º'
  - 'EC'
  - 'MC'
  - 'LC'
  - 'TE'
  - 'PC'
  - 'U1'
  - 'U2'
  - 'U3'
sel_cluster_order:
  - 'Spermatogonia'
  - 'Early 1º Spermatocytes'
  - 'Mid 1º Spermatocytes'
  - 'Late 1º Spermatocytes'
  - 'Early Cyst Cells'
  - 'Mid Cyst Cells'
  - 'Late Cyst Cells'
  - 'Terminal Epithelium'
  - 'Pigment Cells'
sel_cluster_order_w_rep:
  - 'Spermatogonia-rep1'
  - 'Spermatogonia-rep2'
  - 'Spermatogonia-rep3'
  - 'Early 1º Spermatocytes-rep1'
  - 'Early 1º Spermatocytes-rep2'
  - 'Early 1º Spermatocytes-rep3'
  - 'Mid 1º Spermatocytes-rep1'
  - 'Mid 1º Spermatocytes-rep2'
  - 'Mid 1º Spermatocytes-rep3'
  - 'Late 1º Spermatocytes-rep1'
  - 'Late 1º Spermatocytes-rep2'
  - 'Late 1º Spermatocytes-rep3'
  - 'Early Cyst Cells-rep1'
  - 'Early Cyst Cells-rep2'
  - 'Early Cyst Cells-rep3'
  - 'Mid Cyst Cells-rep1'
  - 'Mid Cyst Cells-rep2'
  - 'Mid Cyst Cells-rep3'
  - 'Late Cyst Cells-rep1'
  - 'Late Cyst Cells-rep2'
  - 'Late Cyst Cells-rep3'
  - 'Terminal Epithelium-rep1'
  - 'Terminal Epithelium-rep2'
  - 'Terminal Epithelium-rep3'
  - 'Pigment Cells-rep1'
  - 'Pigment Cells-rep2'
  - 'Pigment Cells-rep3'
chrom_order:
  - chrX
  - chr2L
  - chr2R
  - chr3L
  - chr3R
  - chr4
  - chrY
