author: Justin M Fear
email: justin.m.fear@gmail.com
project: Larval Gonad
git: https://github.com/jfear/larval_gonad
#references_dir: <path to references> defaults to environmental variable
assembly: dmel
tag: r6-16
fliersprops:
  alpha: .1
formats:
  - png
  - pdf
styles:
  - notebook
  - paper
  - talk
resolution: 'res.0.6'
cluster_annot:
  0: 'Late 1º Spermatocytes (0)'
  1: 'Mid Cyst Cells (1)'
  2: 'Mid 1º Spermatocytes (2)'
  3: 'Early 1º Spermatocytes (3)'
  4: 'Late Cyst Cells (4)'
  5: 'Early Cyst Cells (5)'
  6: 'Spermatogonia (6)'
  7: 'Terminal Epithelium (7)'
  8: 'Pigment Cells (8)'
  9: 'Unknown (9)'
  10: 'Unknown (10)'
  11: 'Unknown (11)'
cluster_order:
  - 'Spermatogonia (6)'
  - 'Early 1º Spermatocytes (3)'
  - 'Mid 1º Spermatocytes (2)'
  - 'Unknown (11)'
  - 'Late 1º Spermatocytes (0)'
  - 'Early Cyst Cells (5)'
  - 'Mid Cyst Cells (1)'
  - 'Late Cyst Cells (4)'
  - 'Unknown (9)'
  - 'Unknown (10)'
  - 'Terminal Epithelium (7)'
  - 'Pigment Cells (8)'
chrom_order:
  - chrX
  - chr2L
  - chr2R
  - chr3L
  - chr3R
  - chr4
  - chrY
