# These genes have been described in the literature. For more details see:
# https://docs.google.com/spreadsheets/d/1A5ilJROL4HUeQOXwJlWuiTjbE1EsJhiWxKUC5lleM4k/edit?usp=sharing

SP:               # spermatogonia
  - FBgn0002962   # nos
  - FBgn0003525   # stg
  - FBgn0052364   # tut
  - FBgn0002932   # neur
  - FBgn0250816   # AGO3
  - FBgn0001981   # esg
  - FBgn0020493   # Dad

SP_ES:            # spermatogonia and early 1ยบ spermatocytes
  - FBgn0031091   # Phf7
  - FBgn0039044   # p53
  - FBgn0000158   # bam
  - FBgn0005672   # spi
  - FBgn0283442   # vas
  - FBgn0004581   # bgcn
  - FBgn0051361   # dpr17
  - FBgn0000146   # Aub
  - FBgn0038089   # d-cup
  - FBgn0000404   # CycA
  - FBgn0000405   # CycB

ES:               # early 1ยบ spermatocytes
  - FBgn0250843   # Prosalpha6

PS:               # 1ยบ spermatocytes
  - FBgn0002842   # sa
  - FBgn0002673   # twe
  - FBgn0039124   # tbrd-1
  - FBgn0031715   # tomb
  - FBgn0041103   # nht
  - FBgn0014342   # mia
  - FBgn0031623   # Taf12L (rye)
  - FBgn0011569   # can
  - FBgn0004372   # aly
  - FBgn0011596   # fzo
  - FBgn0019828   # dj
  - FBgn0011206   # bol
  - FBgn0039071   # bb8
  - FBgn0033476   # oys (oysgedart)
  - FBgn0002862   # Mst87F
  - FBgn0030313   # CG11697
  - FBgn0032473   # CG5204 (kmg)
  - FBgn0034739   # CG3927
  - FBgn0010258   # Rbp4
  - FBgn0034435   # fest
  - FBgn0037751   # topi

LS:               # late 1ยบ spermatocytes
  - FBgn0041102   # ocn

EC:               # Early Cyst Cells
  - FBgn0002543   # robo2
  - FBgn0004606   # Zfh1
  - FBgn0003984   # vn
  - FBgn0024234   # gbb
  - FBgn0000964   # tj
  - FBgn0003964   # usp
  - FBgn0001257   # ImpL2
  - FBgn0010453   # Wnt4
  - FBgn0004108   # nrt
  - FBgn0001090   # bnb
  - FBgn0011591   # fng
  - FBgn0000546   # EcR
  - FBgn0243512   # puc
  - FBgn0014163   # fax
  - FBgn0283451   # Br
  - FBgn0032451   # spict
  - FBgn0003366   # sev
  - FBgn0003460   # so

CY:               # Cyst Cells
  - FBgn0004872   # piwi
  - FBgn0000320   # eya
  - FBgn0034408   # sano
  - FBgn0015399   # kek1
  - FBgn0083963   # Nlg3
  - FBgn0038180   # Cht5
  - FBgn0243486   # rdo

TE:               # Terminal epithelia
  - FBgn0050418   # nord
  - FBgn0000395   # cv-2
  - FBgn0264953   # Piezo
  - FBgn0004647   # N
  - FBgn0000014   # abd-A
  - FBgn0000015   # Abd-B

PC:               # Pigment cells
  - FBgn0024288   # Sox100B
  - FBgn0000576   # ems

H:                # Hub
  - FBgn0004956   # upd1
  - FBgn0004644   # hh
  - FBgn0264089   # slit
  - FBgn0041184   # Socs36E
  - FBgn0262169   # magu
  - FBgn0000636   # Fas3
