# These genes have been described in the literature. For more details see:
# https://docs.google.com/spreadsheets/d/1A5ilJROL4HUeQOXwJlWuiTjbE1EsJhiWxKUC5lleM4k/edit?usp=sharing

G:                # spermatogonia
  - FBgn0250816   # AGO3
  - FBgn0000146   # aub
  - FBgn0283442   # vas
  - FBgn0000158   # bam
  - FBgn0039044   # p53
  - FBgn0026533   # Dek (p-trap)
  - FBgn0087008   # e(y)3 (p-trap)
G_EPS:            # spermatogonia and early 1ยบ spermatocytes
  - FBgn0010258   # Rbp4
  - FBgn0031091   # Phf7
  - FBgn0031715   # tomb
  - FBgn0032473   # CG5204 (kmg)
  - FBgn0034282   # Mapmodulin (p-trap)
  - FBgn0041103   # nht
  - FBgn0262743   # Fs(2)Ket
  - FBgn0286813   # SRPK (p-trap)
EPS:
  - FBgn0004372   # aly
  - FBgn0002842   # sa
  - FBgn0039124   # tbrd-1
  - FBgn0026573   # ADD1 (p-trap)
EPS_MPS_LPS:
  - FBgn0002673   # twe
  - FBgn0011206   # bol
  - FBgn0003475   # spir (p-trap)
  - FBgn0011596   # fzo
  - FBgn0012037   # Ance (p-trap)
  - FBgn0019828   # dj
  - FBgn0041102   # ocn
  - FBgn0051361   # dpr17 (p-trap)
  - FBgn0000405   # CycB
  - FBgn0002862   # Mst87F
  - FBgn0011725   # twin (p-trap)
  - FBgn0030313   # CG11697
  - FBgn0034435   # fest
  - FBgn0034739   # CG3927
  - FBgn0039071   # bb8
G_EPS_MPS_LPS:
  - FBgn0000404   # CycA
  - FBgn0031623   # Taf12L
mixed:
  - FBgn0000416   # Sap-r (p-trap)
  - FBgn0030520   # Pdcd4 (p-trap)
  - FBgn0250843   # Prosalpha6
  - FBgn0261885   # osa (p-trap)
  - FBgn0266521   # stai (p-trap)
cyst:
  - FBgn0000320   # eya
  - FBgn0083963   # Nlg3 (p-trap)
  - FBgn0051158   # Efa6 (p-trap)
  - FBgn0264494   # CG17646 (p- trap)
  - FBgn0004872   # piwi
  - FBgn0011591   # fng
  - FBgn0038197   # foxo (p- trap)
  - FBgn0039754   # CG9747 (p- trap)
  - FBgn0000964   # tj
  - FBgn0243486   # rdo (p- trap)
  - FBgn0001090   # bnb
  - FBgn0004108   # Nrt
  - FBgn0010453   # Wnt4
T:
  - FBgn0050418   # nord (p- trap)
  - FBgn0264953   # Piezo (p- trap)
  - FBgn0000636   # Fas3 (p- trap)
  - FBgn0010473   # tutl
P:
  - FBgn0000576   # ems
  - FBgn0004885   # tok (p- trap)
  - FBgn0024288   # Sox100B
somatic:
  - FBgn0001257   # ImpL2
  - FBgn0003984   # vn
  - FBgn0004647   # N
  - FBgn0014163   # fax
  - FBgn0015399   # kek1
  - FBgn0020493   # Dad
  - FBgn0027598   # cindr (p- trap)
  - FBgn0041182   # Tep2 (p- trap)
  - FBgn0243512   # puc
  - FBgn0264975   # Nrg (p- trap)
  - FBgn0265487   # mbl (p- trap)
