# List of T2A Gal4 lines we have looked at.
lit_genes:
#GSC, spermatogonia, early spermatocytes
  - 'vas'
  - 'Phf7'
  - 'CG11697'
  - 'p53'
  - 'nos'
  - 'bgcn'
  - 'bam'
  - 'tut'
  - 'Rbp9'
  - 'peb'
  - 'tej'
  - 'Marf'
# Later spermatocytes and spermatids
  - 'nht'
  - 'can'
  - 'aly'
  - 'fzo'
  - 'soti'
  - 'dj'
  - 'bol'
  - 'ocn'
  - 'mle'
  - 'mia'
  - 'CG3927'
  - 'sunz'
  - 'sowi'
  - 'c-cup'
  - 'd-cup'
  - 'wa-cup'
  - 'p-cup'
  - 'r-cup'
  - 'oys'
  - 'topi'
  - 'sa'
  - 'CG8368'
# Enriched in CySC lineage
  - 'zfh1'
  - 'vn'
  - 'foxo'
  - 'apt'
  - 'ImpL2'
  - 'Wnt4'
  - 'Nrt'
  - 'bnb'
  - 'neur'
  - 'robo2'
  - 'EcR'
  - 'gbb'
  - 'spict'
  - 'puc'
  - 'sev'
  - 'tj'
  - 'hui'
  - 'sano'
  - 'eya'
  - 'glob1'
  - 'Eip93F'
  - 'fax'
  - 'kek1'
  - 'so'
# Terminal epithelia
  - 'nord'
  - 'retn'
  - 'abd-A'
  - 'Abd-B'
  - 'Wnt2'
  - 'Six4'
  - 'CG18628'
  - 'MtnA'
  - 'N'
# Pigment cells
  - 'vkg'
  - 'Sox100B'
  - 'bw'
  - 'ems'
# Genes in multiple cell types
  - 'chinmo'
  - 'His2Av'
  - 'Diap1'
  - 'Diap2'
  - 'Socs36E'
  - 'hdc'
  - 'how'
  - 'msi'
  - 'ken'
  - 'piwi'
# Other important markers
  - 'stg'
  - 'twe'
  - 'esg'

t2a:
  - 'vari'
  - 'CG42458'
  - 'CG34383'
  - 'CG34394'
  - 'CG7255'
  - 'Wnt4'
  - 'cv-2'
  - 'Eaf'
  - 'tun'
  - 'Zasp52'
  - 'Su(var)2-10'
  - 'GEFmeso'
  - 'ths'
  - 'pk'
  - 'rdo'
  - 'bin3'
  - 'CG2082'
  - 'Khc-73'
  - 'FER'
  - 'CG31075'
  - 'QC'
  - 'dally'
  - 'CG11658'
  - 'PyK'
  - 'PH4alphaEFB'
  - 'RasGAP1'
  - 'Ino80'

# List of GAL4 lines we have looked at
gal4:
  - 'CG11658'
  - 'Notum'
  - 'CadN '
  - 'Tsp74F'
  - 'sano'
  - 'rau'
  - 'CG32354'
  - 'trn'
  - 'Irk1'
  - 'bnl'
  - 'hng3'
  - 'tkv'
  - 'CG34383'
  - 'CG34323'
  - 'qjt'
  - 'qin'
  - 'qin'
  - 'klu'
  - 'CR46216'
  - 'mael'
  - 'CG9272'
  - 'CR33319'
  - 'Grx1t'
  - 'CG43059'
  - 'CG6888'
  - 'CG4218'
  - 'CR44852'
  - 'CG31644'
  - 'bol'
  - 'svp'
  - 'svp'
  - 'CG4822'
  - 'Meltrin'
  - 'Fili'
  - 'Papss'
  - 'AdamTS-A'
  - 'cdi'
  - 'eya'
  - 'CG42673'

# List of Ben White's T2A gal4 that we have looked at.
white:
  - 'AkhR'
  - 'burs'
  - 'CG2187'
  - 'ChaT'
  - 'CrzR'
  - 'Dh31R'
  - 'EH'
  - 'EHR'
  - 'ETHR'
  - 'ETHR'
  - 'ETHRB'
  - 'GluRIIB'
  - 'HR46'
  - 'HR46'
  - 'LGR1'
  - 'pburs'
  - 'Proc'
  - 'ProcR'
  - 'rk'

# List of protein traps that Erika has looked at.
protein_trap_genes:
  - 'ADD1'
  - 'Ance'
  - 'bbg'
  - 'bol'
  - 'CadN'
  - 'CG11044'
  - 'CG17349'
  - 'CG17646'
  - 'CG3277'
  - 'CG42321'
  - 'CG43088'
  - 'CG43373'
  - 'CG6356'
  - 'CG8036'
  - 'CG8851'
  - 'CG9747'
  - 'cindr'
  - 'Dek'
  - 'DIP-delta'
  - 'dlp'
  - 'dpr17'
  - 'dpr3'
  - 'dsx'
  - 'Efa6'
  - 'egr'
  - 'eIF5B'
  - 'e(y)3'
  - 'Fas3'
  - 'foxo'
  - 'fru'
  - 'Fs(2)Ket'
  - 'hid'
  - 'ImpL2'
  - 'klu'
  - 'LRP1'
  - 'Mapmodulin'
  - 'mbl'
  - 'Mi-2'
  - 'NetA'
  - 'NFAT'
  - 'nkd'
  - 'nord'
  - 'Nrg'
  - 'osa'
  - 'p130CAS'
  - 'p53'
  - 'Pdcd4'
  - 'Pde11'
  - 'Piezo'
  - 'ppan'
  - 'Ptp4E'
  - 'Pvr'
  - 'Rab3'
  - 'Reck'
  - 'Sap-r'
  - 'sdk'
  - 'Sox102F'
  - 'spir'
  - 'SRPK'
  - 'stai'
  - 'stg'
  - 'svp'
  - 'Ten-a'
  - 'Ten-m'
  - 'Tep2'
  - 'tok'
  - 'tutl'
  - 'twin'
  - 'Vha68-3'
  - 'Wdr62'
  - 'wnd'
