data_pattern: 
  cellranger-wf: '../output/cellranger-wf/{sample}/outs/filtered_gene_bc_matrices/{assembly}{tag}/matrix.mtx'
  cellranger-force-wf: '../output/cellranger-force-wf/{sample}/outs/filtered_gene_bc_matrices/{assembly}{tag}/matrix.mtx'
  cellranger3-wf: '../output/cellranger3-wf/{sample}/outs/filtered_feature_bc_matrix/matrix.mtx'