---
title: Monocle 3 Testis 1 Clustering
author: Justin Fear
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
output:
    html_document:
        self_contained: TRUE
        keep_md: TRUE
---

## Testis 1

Here I explore clustering using Monocle v3 for clustering.

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    warning = FALSE,
    message = FALSE,
    include = TRUE,
    echo = FALSE,
    cache.lazy = FALSE,
    fig.path = "testis1_figures/",
    fig.ext = c("png", "svg"),
    fig.width = 8
)
```

```{r install.monocle3.alpha, eval=FALSE}
devtools::install_github("cole-trapnell-lab/monocle3")
```

```{r load_libraries}
library(monocle3)
library(dplyr)
library(ggplot2)
set.seed(42)
```

```{r globals}
SAMPLE <- "testis1"
NUM_DIMS <- 9

PROJ_DIR <- "/home/fearjm/Projects/larval_gonad"
DATA_DIR <- file.path(PROJ_DIR, paste0("output/cellselection-wf/", SAMPLE))
OUTDIR <- file.path(PROJ_DIR, "output/monocle3-cluster-wf")

GENE_ANNOTATION <- file.path(PROJ_DIR, "references/gene_annotation_dmel_r6-26.feather")
LITERATURE_GENES <- file.path(PROJ_DIR, "config/literature_genes.yaml")
```

```{r load_gene_annotations}
fbgn2symbol <- feather::read_feather(
    GENE_ANNOTATION,
    columns = c("FBgn", "gene_symbol")
)
```

```{r load_cellranger_data}
# Load feature data
genes <- tibble(FBgn = read.table(file.path(DATA_DIR, "genes.tsv"), stringsAsFactors = FALSE)[,1]) %>%
    left_join(., fbgn2symbol) %>% 
    tibble::column_to_rownames("FBgn") %>% 
    rename(gene_short_name = gene_symbol)

# Load cell sample data
cells <- tibble(cell_id = read.table(file.path(DATA_DIR, "barcodes.tsv"), stringsAsFactors = FALSE)[,1]) %>%
    mutate(sample = SAMPLE) %>%
    tibble::column_to_rownames("cell_id")

# Load matrix
mtx <- Matrix::readMM(file.path(DATA_DIR, "matrix.mtx"))
colnames(mtx) <- row.names(cells)
rownames(mtx) <- row.names(genes)

# Build CDS
cds <- new_cell_data_set(mtx, cell_metadata = cells, gene_metadata = genes)
```

```{r preprocess}
cds <- preprocess_cds(cds)
```

```{r elbow_plot}
plot_pc_variance_explained(cds)
```

```{r reduce_dims}
cds <- reduce_dimension(cds)
```


```{r cluster}
cds = cluster_cells(cds, resolution=c(10^seq(-6,-1)))
plot_cells(cds)
```






### Look at marker genes

```{r load_lit_genes}
lit_genes <- yaml::yaml.load_file(LITERATURE_GENES)
```

## Spermatogonia
```{r fig.width=8, fig.height=12}
markers <- fData(cds)[lit_genes$G,]
plot_cells(cds, genes = markers, label_cell_groups = FALSE)
```

## Primary Spermatocytes
```{r fig.width=8, fig.height=20}
markers <- fData(cds)[lit_genes$EPS_MPS_LPS,]
plot_cells(cds, genes = markers, label_cell_groups = FALSE)
```

## CySC
```{r fig.width=8, fig.height=20}
markers <- fData(cds)[lit_genes$cyst,]
plot_cells(cds, genes = markers, label_cell_groups = FALSE)
```

## Terminal Epithelium
```{r fig.width=8, fig.height=12}
markers <- fData(cds)[lit_genes$T,]
plot_cells(cds, genes = markers, label_cell_groups = FALSE)
```

## Pigment Cells
```{r fig.width=8, fig.height=6}
markers <- fData(cds)[lit_genes$P,]
plot_cells(cds, genes = markers, label_cell_groups = FALSE)
```

```{r trajectory}
cds <- learn_graph(cds)
plot_cells(cds, 
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_branch_points=FALSE)
```



```{r save_robj}
save(
    tesits1 = cds,
    file = file.path(OUTDIR, paste(SAMPLE, "Robj", sep = "."))
)
```

```{r metadata}
clusters <- tibble::as_tibble(
    as.data.frame(cds@clusters$UMAP$clusters) %>%
        tibble::rownames_to_column("cell_id") %>%
        mutate(clusters = .[, 2]) %>%
        select(cell_id, clusters)
)

df <- tibble::as_tibble(
    pData(cds) %>%
        as.data.frame() %>%
        tibble::rownames_to_column("cell_id") %>%
        left_join(clusters)
)

write.table(
    df,
    file = file.path(OUTDIR, paste(SAMPLE, "clusters.tsv", sep = "_")),
    sep = "\t",
    quote = FALSE,
    row.names = FALSE,
    col.names = TRUE
)

feather::write_feather(df,
    path = file.path(OUTDIR, paste(SAMPLE, "clusters.feather", sep = "_"))
)
```
