channels:
    - bioconda
    - r
    - defaults
    - conda-forge
dependencies:
    - kallisto==0.43.0
    - snakemake==3.9
    - bowtie2==2.2.8
    - hisat2==2.0.5
    - picard==2.7.1
    - ucsc-gtftogenepred==332
    - python==3.5
    - salmon ==0.8.2
