---
title: Monocle Pseudotime Analysis With Clustering
author: Justin Fear
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
---

```{r, include=FALSE}
knitr::opts_chunk$set(collapse=TRUE, warning=FALSE, message=FALSE, cache.lazy=FALSE,
                      bootstrap.show.code=FALSE, bootstrap.show.output=FALSE,
                      fig.ext='png')
```

```{r setup}
options(repr.plot.width=10, repr.plot.height=10)
library('monocle')
library('dplyr')
library('gridExtra')
```

```{r, get.gene.annot}
# create a dataframe with FBgn to gene symbol
genes <- read.table('/data/LCDB/lcdb-references/dmel/r6-16/fb_annotation/dmel_r6-16.fb_annotation',
		    sep='\t',
		    stringsAsFactors=F,
		    header=T,
		    quote=NULL,
		    colClasses=c(rep("character", 2), rep("NULL", 3))
		    )
colnames(genes) <- c('gene_symbo', 'FBgn')
row.names(genes) <- genes$FBgn
```


```{r load.seurat}
# Load data from seurat object.
load('../scrnaseq-wf/data/scrnaseq_combine_force/seurat.Robj')
sobj <- object
dds <- importCDS(sobj)
```

I am assuming the following annotations:

* 0: 'Late 1ยบ Spermatocytes (0)'
* 1: 'Mid Cyst Cells (1)'
* 2: 'Mid 1ยบ Spermatocytes (2)'
* 3: 'Early 1ยบ Spermatocytes (3)'
* 4: 'Late Cyst Cells (4)'
* 5: 'Early Cyst Cells (5)'
* 6: 'Spermatogonia (6)'
* 7: 'Terminal Epithelium (7)'
* 8: 'Pigment Cells (8)'
* 9: 'Unknown (9)'
* 10: 'Unknown (10)'
* 11: 'Unknown (11)'

```{r get.germ}
# Pull out only the germ cells based on res.0.6
germ <- row.names(subset(pData(dds), res.0.6 %in% c(0, 2, 3, 6, 11)))
dds_germ <- dds[, germ]
```

```{r add.gene.annot}
# Add on gene symbols to make easier to read
merged <- left_join(fData(dds_germ), genes, by=c('gene_short_name' = 'FBgn'))
row.names(merged) <- merged$gene_short_name
colnames(merged) <- c('FBgn', 'gene_short_name')
fData(dds_germ) <- merged
```

```{r estimate.norms}
# Detect expressed genes and normalize
dds_germ <- estimateSizeFactors(dds_germ)
dds_germ <- estimateDispersions(dds_germ)
dds_germ <- detectGenes(dds_germ, min_expr = 0.1)
```

```{r celltype.hierarchy}
cth <- newCellTypeHierarchy()

# Spermatogonia
p53 <- row.names(subset(fData(dds_germ), gene_short_name  == 'p53'))
cth <- addCellType(cth, "Gonia", classify_fun = function(x) { x[p53,] > 0 })

# Early Spermatocytes
vas <- row.names(subset(fData(dds_germ), gene_short_name  == 'vas'))
cth <- addCellType(cth, "Early", classify_fun = function(x) { x[vas,] > 0 })

# Mid Spermatocytes
aly <- row.names(subset(fData(dds_germ), gene_short_name  == 'aly'))
cth <- addCellType(cth, "Mid", classify_fun = function(x) { x[aly,] > 0 })

# Late Spermatocytes
dj <- row.names(subset(fData(dds_germ), gene_short_name  == 'dj'))
cth <- addCellType(cth, "Late", classify_fun = function(x) { x[dj,] > 0 })
```

```{r classify.cells}
dds_germ <- classifyCells(dds_germ, cth, 0.1)
table(pData(dds_germ)$CellType)
```

```{r plot.celltype}
png('data/supervised_cell_type.png')
pie <- ggplot(pData(dds_germ),
aes(x = factor(1), fill = factor(CellType))) + geom_bar(width = 1)
pie + coord_polar(theta = "y") +
theme(axis.title.x = element_blank(), axis.title.y = element_blank())
dev.off()
```

```{r cluster.celltype}
expressed_genes <- row.names(subset(fData(dds_germ), num_cells_expressed >= 10))

marker_diff <- markerDiffTable(dds_germ[expressed_genes,],
            cth,
            residualModelFormulaStr = "~rep + num_genes_expressed",
            cores = 1)
```

```{r}
semisup_clustering_genes <- row.names(marker_diff)[order(marker_diff$qval)][1:1000]
dds_germ <- setOrderingFilter(dds_germ, semisup_clustering_genes)
dds_germ <- reduceDimension(dds_germ, max_components = 2, method = 'DDRTree', norm_method = 'log')
dds_germ <- orderCells(dds_germ)
```

```{r}
Gonia_state <- function(cds){
  if (length(unique(pData(cds)$State)) > 1){
    T0_counts <- table(pData(cds)$State, pData(cds)$CellType)[,"Gonia"]
    return(as.numeric(names(T0_counts)[which
          (T0_counts == max(T0_counts))]))
  } else {
    return (1)
  }
}
```


```{r}
dds_germ <- orderCells(dds_germ, root_state = Gonia_state(dds_germ))
```

```{r}
png('data/supervised_tree.png')
plot_cell_trajectory(dds_germ, color_by = "CellType") + theme(legend.position = "right")
def.off()
```
