channels:
- jfear
- bioconda
- conda-forge
- defaults
- lcdb
dependencies:
- atropos=1.1.18=py36_0
- bcftools=1.7=0
- bedtools=2.27.1=1
- bioconductor-annotate=1.56.0=r3.4.1_0
- bioconductor-annotationdbi=1.40.0=r3.4.1_0
- bioconductor-annotationhub=2.10.1=r3.4.1_0
- bioconductor-biobase=2.38.0=r3.4.1_0
- bioconductor-biocgenerics=0.24.0=r3.4.1_0
- bioconductor-biocinstaller=1.28.0=r3.4.1_0
- bioconductor-biocparallel=1.12.0=r3.4.1_0
- bioconductor-biomart=2.34.2=r3.4.1_0
- bioconductor-biostrings=2.46.0=r3.4.1_0
- bioconductor-clusterprofiler=3.6.0=r3.4.1_0
- bioconductor-delayedarray=0.4.1=r3.4.1_0
- bioconductor-deseq2=1.18.1=r3.4.1_1
- bioconductor-do.db=2.9=r3.4.1_1
- bioconductor-dose=3.4.0=r3.4.1_0
- bioconductor-dupradar=1.8.0=r3.4.1_1
- bioconductor-fgsea=1.4.0=r3.4.1_0
- bioconductor-genefilter=1.60.0=r3.4.1_0
- bioconductor-geneplotter=1.56.0=r3.4.1_0
- bioconductor-genomeinfodb=1.14.0=r3.4.1_0
- bioconductor-genomeinfodbdata=1.0.0=r3.4.1_1
- bioconductor-genomicalignments=1.14.1=r3.4.1_0
- bioconductor-genomicfeatures=1.28.5=r3.4.1_0
- bioconductor-genomicranges=1.30.3=r3.4.1_0
- bioconductor-go.db=3.5.0=r3.4.1_1
- bioconductor-gosemsim=2.4.0=r3.4.1_0
- bioconductor-interactivedisplaybase=1.16.0=r3.4.1_0
- bioconductor-iranges=2.12.0=r3.4.1_0
- bioconductor-limma=3.34.9=r3.4.1_0
- bioconductor-qvalue=2.10.0=r3.4.1_0
- bioconductor-rsamtools=1.30.0=r3.4.1_0
- bioconductor-rsubread=1.28.1=r3.4.1_0
- bioconductor-rtracklayer=1.38.3=r3.4.1_0
- bioconductor-s4vectors=0.16.0=r3.4.1_0
- bioconductor-summarizedexperiment=1.8.0=r3.4.1_0
- bioconductor-sva=3.26.0=r3.4.1_0
- bioconductor-tximport=1.6.0=r3.4.1_0
- bioconductor-xvector=0.18.0=r3.4.1_0
- bioconductor-zlibbioc=1.24.0=r3.4.1_0
- biopython=1.70=np112py36_1
- bowtie=1.2.2=py36pl5.22.0_0
- bowtie2=2.3.4.1=py36pl5.22.0_0
- cutadapt=1.16=py36_1
- deeptools=3.0.2=py36_0
- fastq-screen=0.11.3=pl5.22.0_0
- fastqc=0.11.7=pl5.22.0_1
- filechunkio=1.6=py36_0
- ftputil=3.2=py36_0
- gat=1.3.5=py36_1
- gffutils=0.9=py36_0
- ghostscript=9.18=1
- hisat2=2.1.0=py36pl5.22.0_0
- htslib=1.7=0
- intervalstats=1.01=0
- jemalloc=4.5.0=0
- kallisto=0.44.0=hdf51.8.17_1
- multiqc=1.5a=py36_0
- mysql-connector-c=6.1.6=2
- perl-gd=2.56=pl5.22.0_6
- perl-gdgraph=1.49=pl5.22.0_3
- perl-gdtextutil=0.86=pl5.22.0_3
- picard=2.18.4=py36_0
- py2bit=0.3.0=py36_0
- pybedtools=0.7.10=py36_2
- pybigwig=0.3.6=np112py36_0
- pyfaidx=0.5.3=py36_0
- pysam=0.14.1=py36_htslib1.7_0
- pysftp=0.2.9=py36_0
- r-data.table=1.10.4=r3.4.1_0
- r-spp=1.15.2=r_3.4.1_boost1.64_0
- salmon=0.9.1=1
- samtools=1.7=2
- simplejson=3.8.1=py36_0
- snakemake=4.4.0=py36_0
- subread=1.6.1=0
- tqdm=4.7.2=py36_0
- trackhub=0.2.4=py36_0
- ucsc-bedsort=357=1
- ucsc-bedtobigbed=357=1
- ucsc-fetchchromsizes=357=1
- ucsc-gtftogenepred=357=1
- ucsc-liftover=357=1
- ucsc-oligomatch=357=1
- ucsc-twobittofa=357=1
- xopen=0.3.2=py36_0
- aioeasywebdav=2.2.0=py36_0
- aiohttp=3.2.1=py36_0
- apipkg=1.4=py36_0
- appdirs=1.4.3=py_0
- argcomplete=1.8.2=py36_0
- argh=0.26.2=py36_1
- asn1crypto=0.24.0=py36_0
- async-timeout=2.0.1=py36_0
- attrs=18.1.0=py_0
- backcall=0.1.0=py_0
- boost=1.64.0=py36_4
- boost-cpp=1.64.0=1
- bzip2=1.0.6=1
- ca-certificates=2018.4.16=0
- cairo=1.14.10=0
- certifi=2018.4.16=py36_0
- cffi=1.11.5=py36_0
- chardet=3.0.4=py36_0
- click=6.7=py_1
- colormath=3.0.0=py_2
- configargparse=0.12.0=py36_0
- cryptography=2.2.1=py36_0
- curl=7.59.0=1
- cycler=0.10.0=py36_0
- cython=0.28.2=py36_0
- dbus=1.11.0=0
- decorator=4.3.0=py_0
- docutils=0.14=py36_0
- dropbox=8.9.0=py_0
- execnet=1.5.0=py_0
- expat=2.2.5=0
- fontconfig=2.12.6=0
- freetype=2.8.1=0
- future=0.16.0=py36_0
- gettext=0.19.8.1=0
- giflib=5.1.4=0
- glib=2.55.0=0
- gmp=6.1.2=0
- graphite2=1.3.11=0
- graphviz=2.38.0=7
- gsl=2.1=2
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=1
- harfbuzz=1.7.6=0
- hdf5=1.8.17=11
- icu=58.2=0
- idna=2.6=py36_1
- idna_ssl=1.0.0=0
- ipython=6.4.0=py36_0
- ipython_genutils=0.2.0=py36_0
- jedi=0.12.0=py36_0
- jinja2=2.10=py36_0
- jpeg=9b=2
- jsonschema=2.6.0=py36_1
- jupyter_core=4.4.0=py_0
- kiwisolver=1.0.1=py36_1
- krb5=1.14.6=0
- libffi=3.2.1=3
- libgd=2.2.5=3
- libiconv=1.15=0
- libpng=1.6.34=0
- libssh2=1.8.0=2
- libtiff=4.0.9=0
- libtool=2.4.6=0
- libuuid=1.0.3=1
- libwebp=0.5.2=7
- libxcb=1.13=0
- libxml2=2.9.8=0
- lzstring=1.0.3=py36_0
- markdown=2.6.11=py_0
- markupsafe=1.0=py36_0
- matplotlib=2.2.2=py36_1
- mmtf-python=1.1.2=py_0
- more-itertools=4.1.0=py_0
- msgpack-python=0.5.6=py36_1
- multidict=4.3.1=py36_0
- nbformat=4.4.0=py36_0
- ncurses=5.9=10
- networkx=2.0=py36_1
- olefile=0.45.1=py36_0
- openssl=1.0.2o=0
- pandas=0.23.0=py36_1
- pandoc=2.2.1=0
- pango=1.40.14=0
- paramiko=2.4.1=py36_0
- parso=0.2.1=py_0
- patsy=0.5.0=py36_0
- pcre=8.39=0
- perl=5.22.0.1=0
- pexpect=4.5.0=py36_0
- pickleshare=0.7.4=py36_0
- pigz=2.3.4=0
- pillow=5.1.0=py36_0
- pip=9.0.3=py36_0
- pixman=0.34.0=2
- plotly=2.6.0=py36_1
- pluggy=0.6.0=py_0
- prompt_toolkit=1.0.15=py36_0
- psutil=5.4.5=py36_0
- ptyprocess=0.5.2=py36_0
- py=1.5.3=py_0
- pyasn1=0.4.2=py_0
- pycparser=2.18=py36_0
- pygments=2.2.0=py36_0
- pynacl=1.1.2=py36_0
- pyopenssl=18.0.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_5
- pysocks=1.6.8=py36_1
- pytest=3.5.1=py36_0
- pytest-forked=0.2=py36_0
- pytest-runner=4.2=py_0
- pytest-xdist=1.22.2=0
- python=3.6.5=1
- python-dateutil=2.7.3=py_0
- pytz=2018.4=py_0
- pyyaml=3.12=py36_1
- qt=5.6.2=7
- r-acepack=1.4.1=r3.4.1_0
- r-assertthat=0.2.0=r3.4.1_0
- r-backports=1.1.2=r3.4.1_0
- r-base=3.4.1=3
- r-base64enc=0.1_3=r3.4.1_0
- r-bh=1.66.0_1=r3.4.1_0
- r-bindr=0.1.1=r3.4.1_0
- r-bindrcpp=0.2=r3.4.1_0
- r-bit=1.1_12=r3.4.1_0
- r-bit64=0.9_5=r3.4.1_0
- r-bitops=1.0_6=r3.4.1_0
- r-blob=1.1.1=r3.4.1_0
- r-catools=1.17.1=r3.4.1_0
- r-checkmate=1.8.2=r3.4.1_0
- r-cli=1.0.0=r3.4.1_0
- r-cluster=2.0.6=r3.4.1_0
- r-codetools=0.2_15=r3.4.1_0
- r-colorspace=1.3_2=r3.4.1_0
- r-crayon=1.3.4=r3.4.1_0
- r-crosstalk=1.0.0=r3.4.1_0
- r-curl=3.2=r3.4.1_0
- r-dbi=1.0.0=r341_0
- r-dichromat=2.0_0=r3.4.1_0
- r-digest=0.6.15=r3.4.1_0
- r-doparallel=1.0.11=r3.4.1_0
- r-dplyr=0.7.4=r3.4.1_0
- r-dt=0.4=r3.4.1_0
- r-evaluate=0.10.1=r3.4.1_0
- r-fastmatch=1.1_0=r3.4.1_0
- r-foreach=1.4.4=r3.4.1_0
- r-foreign=0.8_67=r3.4.1_0
- r-formula=1.2_1=r3.4.1_0
- r-futile.logger=1.4.3=r3.4.1_0
- r-futile.options=1.0.0=r3.4.1_0
- r-gdata=2.18.0=r3.4.1_0
- r-getopt=1.20.0=r3.4.1_0
- r-ggplot2=2.2.1=r3.4.1_0
- r-glue=1.2.0=r3.4.1_0
- r-gplots=3.0.1=r3.4.1_0
- r-gridbase=0.4_7=r3.4.1_0
- r-gridextra=2.3=r3.4.1_0
- r-gtable=0.2.0=r3.4.1_0
- r-gtools=3.5.0=r3.4.1_0
- r-highr=0.6=r3.4.1_0
- r-hmisc=4.0_3=r3.4.1_0
- r-hms=0.3=r3.4.1_0
- r-htmltable=1.9=r3.4.1_0
- r-htmltools=0.3.6=r3.4.1_0
- r-htmlwidgets=1.0=r3.4.1_0
- r-httpuv=1.3.6.2=r3.4.1_0
- r-httr=1.3.1=r3.4.1_0
- r-igraph=1.2.1=r3.4.1_0
- r-irlba=2.3.2=r3.4.1_0
- r-iterators=1.0.9=r3.4.1_0
- r-jsonlite=1.5=r3.4.1_0
- r-kernsmooth=2.23_15=r3.4.1_0
- r-knitr=1.20=r3.4.1_0
- r-knitrbootstrap=1.0.1=r3.4.1_0
- r-labeling=0.3=r3.4.1_0
- r-lambda.r=1.2=r3.4.1_0
- r-lattice=0.20_34=r3.4.1_0
- r-latticeextra=0.6_28=r3.4.1_0
- r-lazyeval=0.2.1=r3.4.1_0
- r-locfit=1.5_9.1=r3.4.1_0
- r-magrittr=1.5=r3.4.1_0
- r-markdown=0.8=r3.4.1_1
- r-mass=7.3_48=r3.4.1_0
- r-matrix=1.2_14=r3.4.1_0
- r-matrixstats=0.53.1=r341_0
- r-memoise=1.1.0=r3.4.1_0
- r-mgcv=1.8_17=r3.4.1_0
- r-mime=0.5=r3.4.1_0
- r-munsell=0.4.3=r3.4.1_0
- r-nlme=3.1_131=r3.4.1_0
- r-nmf=0.21.0=r3.4.1_0
- r-nnet=7.3_12=r3.4.1_0
- r-openssl=1.0.1=r3.4.1_0
- r-pheatmap=1.0.8=r3.4.1_0
- r-pillar=1.2.2=r341_0
- r-pkgconfig=2.0.1=r3.4.1_0
- r-pkgmaker=0.22=r3.4.1_0
- r-plogr=0.1_1=r3.4.1_0
- r-plyr=1.8.4=r3.4.1_0
- r-prettyunits=1.0.2=r3.4.1_0
- r-progress=1.1.2=r3.4.1_0
- r-purrr=0.2.4=r3.4.1_0
- r-r6=2.2.2=r3.4.1_0
- r-rcolorbrewer=1.1_2=r3.4.1_0
- r-rcpp=0.12.15=r3.4.1_0
- r-rcpparmadillo=0.7.800.2.0=r3.4.1_0
- r-rcurl=1.95_4.8=r3.4.1_0
- r-readr=1.1.1=r3.4.1_0
- r-registry=0.5=r3.4.1_0
- r-reshape2=1.4.3=r3.4.1_0
- r-rjson=0.2.15=r3.4.1_0
- r-rlang=0.2.0=r3.4.1_0
- r-rmarkdown=1.9=r341_0
- r-rngtools=1.2.4=r3.4.1_0
- r-rpart=4.1_13=r3.4.1_0
- r-rprojroot=1.3_2=r3.4.1_0
- r-rsqlite=2.0=r3.4.1_0
- r-rvcheck=0.0.9=r3.4.1_0
- r-scales=0.5.0=r3.4.1_0
- r-shiny=1.0.5=r3.4.1_0
- r-snow=0.4_2=r3.4.1_0
- r-sourcetools=0.1.6=r3.4.1_0
- r-stringi=1.1.7=r3.4.1_1
- r-stringr=1.3.0=r3.4.1_0
- r-survival=2.40_1=r3.4.1_0
- r-tibble=1.4.2=r3.4.1_0
- r-tidyr=0.8.0=r3.4.1_0
- r-tidyselect=0.2.4=r3.4.1_0
- r-utf8=1.1.3=r3.4.1_0
- r-viridis=0.5.1=r3.4.1_0
- r-viridislite=0.3.0=r3.4.1_0
- r-xml=3.98_1.6=r3.4.1_0
- r-xtable=1.8_2=r3.4.1_0
- r-yaml=2.1.18=r3.4.1_0
- ratelimiter=1.2.0=py36_0
- readline=7.0=0
- requests=2.18.4=py36_1
- seaborn=0.8.1=py36_0
- setuptools=39.2.0=py36_0
- simplegeneric=0.8.1=py36_0
- sip=4.18=py36_1
- six=1.11.0=py36_1
- spectra=0.0.11=py_0
- sqlite=3.20.1=2
- statsmodels=0.9.0=py36_0
- tbb=2018_20171205=0
- tk=8.6.7=0
- tornado=5.0.2=py36_0
- traitlets=4.3.2=py36_0
- urllib3=1.22=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.31.0=py36_0
- wrapt=1.10.11=py36_0
- xorg-kbproto=1.0.7=1
- xorg-libice=1.0.9=2
- xorg-libsm=1.2.2=2
- xorg-libx11=1.6.5=0
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- xorg-libxext=1.3.3=2
- xorg-libxrender=0.9.10=0
- xorg-renderproto=0.11.1=1
- xorg-xextproto=7.3.0=1
- xorg-xproto=7.0.31=6
- xz=5.2.3=0
- yaml=0.1.7=0
- yarl=1.2.3=py36_0
- zlib=1.2.11=0
- bcrypt=3.1.3=py36_0
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- mkl=2017.0.3=0
- numpy=1.12.1=py36_0
- openjdk=8.0.121=1
- reportlab=3.4.0=py36_0
- scipy=0.19.1=np112py36_0
- wget=1.18=0
- lcdblib=0.1.3=py36_0
