---
title: Monocle2 Testis 1 Clustering
author: Justin Fear
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
output:
    html_document:
        self_contained: TRUE
        keep_md: TRUE
---

## Testis 1

Here I explore clustering using Monocle v2 for clustering.

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    warning = FALSE,
    message = FALSE,
    include = TRUE,
    echo = FALSE,
    cache.lazy = FALSE,
    fig.path = "testis1_figures/",
    fig.ext = c("png", "svg"),
    fig.width = 8
)
```

```{r load_libraries}
library(monocle)
library(dplyr)
library(ggplot2)
set.seed(42)
```

```{r globals}
SAMPLE <- "testis1"
NUM_DIMS <- 9

PROJ_DIR <- "/home/fearjm/Projects/larval_gonad"
DATA_DIR <- file.path(PROJ_DIR, paste0("output/cellselection-wf/", SAMPLE))
OUTDIR <- file.path(PROJ_DIR, "output/monocle2-cluster-wf")

GENE_ANNOTATION <- file.path(PROJ_DIR, "references/gene_annotation_dmel_r6-26.feather")
LITERATURE_GENES <- file.path(PROJ_DIR, "config/literature_genes.yaml")
```

```{r load_gene_annotations}
fbgn2symbol <- feather::read_feather(
    GENE_ANNOTATION,
    columns = c("FBgn", "gene_symbol")
)
```

```{r load_cellranger_data}
# Load feature data
genes <- tibble(FBgn = read.table(file.path(DATA_DIR, "genes.tsv"), stringsAsFactors = FALSE)[,1]) %>%
    left_join(., fbgn2symbol) %>% 
    tibble::column_to_rownames("FBgn") %>% 
    rename(gene_short_name = gene_symbol)

# Load cell sample data
cells <- tibble(cell_id = read.table(file.path(DATA_DIR, "barcodes.tsv"), stringsAsFactors = FALSE)[,1]) %>%
    mutate(sample = SAMPLE) %>%
    tibble::column_to_rownames("cell_id")

# Load matrix
mtx <- readMM(file.path(DATA_DIR, "matrix.mtx"))
colnames(mtx) <- row.names(cells)
rownames(mtx) <- row.names(genes)

# Build CDS
fd <- new("AnnotatedDataFrame", data = genes)
pd <- new("AnnotatedDataFrame", data = cells)
cds <- newCellDataSet(mtx, phenoData = pd, featureData = fd, expressionFamily = negbinomial.size())
```

### Normalize Data

```{r normalize}
cds <- estimateSizeFactors(cds)
cds <- estimateDispersions(cds)
cds <- detectGenes(cds, min_expr = 0.1)
```

```{r plot_standardized_counts}
L <- log(exprs(cds))
melted_dens_df <- reshape2::melt(Matrix::t(scale(Matrix::t(L))))
qplot(value, geom = "density", data = melted_dens_df) +
    stat_function(fun = dnorm, size = 0.5, color = "red") +
    xlab("Standardized log(FPKM)") +
    ylab("Density")
```

### Find VAriable Genes

```{r find_variable_genes}
# ID what genes to use for clustering based on variability.
dispersion_table <- dispersionTable(cds)
unsup_clustering_genes <- subset(dispersion_table, mean_expression >= 0.1)
cds <- setOrderingFilter(cds, unsup_clustering_genes$gene_id)
plot_ordering_genes(cds)
```

### Dimensionality Reduction

```{r elbow_plot}
plot_pc_variance_explained(cds, return_all = FALSE)
```

```{r reduce_dims}
cds <- reduceDimension(cds, max_components = 2, num_dim = NUM_DIMS, reduction_method = "tSNE", verbose = T)
```

### Clustering

```{r cluster_cells}
cds <- clusterCells(cds, num_clusters = 12)
```

```{r fig.width=8, fig.height=8}
plot_cell_clusters(cds, 1, 2)
```

### Look at marker genes

```{r load_lit_genes}
lit_genes <- yaml::yaml.load_file(LITERATURE_GENES)
```

## Spermatogonia
```{r fig.width=8, fig.height=12}
markers <- fData(cds)[lit_genes$gonia,]$gene_short_name
plot_cell_clusters(cds, 1, 2, marker=markers, option = "B")
```

## Primary Spermatocytes
```{r fig.width=8, fig.height=12}
markers <- fData(cds)[lit_genes$spermatocytes,]$gene_short_name
plot_cell_clusters(cds, 1, 2, marker=markers, option = "B")
```

## CySC
```{r fig.width=8, fig.height=12}
markers <- fData(cds)[lit_genes$cysc,]$gene_short_name
plot_cell_clusters(cds, 1, 2, marker=markers, option = "B")
```

## Terminal Epithelium
```{r fig.width=8, fig.height=10}
markers <- fData(cds)[lit_genes$te,]$gene_short_name
plot_cell_clusters(cds, 1, 2, marker=markers, option = "B")
```

## Pigment Cells
```{r fig.width=8, fig.height=6}
markers <- fData(cds)[lit_genes$pigment,]$gene_short_name
plot_cell_clusters(cds, 1, 2, marker=markers, option = "B")
```

## Hub
```{r fig.width=8, fig.height=10}
markers <- fData(cds)[lit_genes$hub,]$gene_short_name
plot_cell_clusters(cds, 1, 2, marker=markers, option = "B")
```

```{r save_robj}
save(
    tesits1 = cds,
    file = file.path(OUTDIR, paste(SAMPLE, "Robj", sep = "."))
)
```

```{r metadata}
df <- tibble::as_tibble(
    pData(cds) %>%
        tibble::rownames_to_column("cell_id") %>%
        rename(clusters = Cluster)
)

write.table(
    df,
    file = file.path(OUTDIR, paste(SAMPLE, "clusters.tsv", sep = "_")),
    sep = "\t",
    quote = FALSE,
    row.names = FALSE,
    col.names = TRUE
)

feather::write_feather(df,
    path = file.path(OUTDIR, paste(SAMPLE, "clusters.feather", sep = "_"))
)
```
